version: 2
project_name: fluxmq

builds:
  - id: fluxmq
    main: ./cmd
    binary: fluxmq
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/absmach/fluxmq.Version={{ .Version }}
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - id: fluxmq
    ids:
      - fluxmq
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
