// Copyright (c) Abstract Machines
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: cluster/v1/broker.proto

package clusterv1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BrokerService_RoutePublish_FullMethodName        = "/fluxmq.cluster.v1.BrokerService/RoutePublish"
	BrokerService_RoutePublishBatch_FullMethodName   = "/fluxmq.cluster.v1.BrokerService/RoutePublishBatch"
	BrokerService_TakeoverSession_FullMethodName     = "/fluxmq.cluster.v1.BrokerService/TakeoverSession"
	BrokerService_FetchRetained_FullMethodName       = "/fluxmq.cluster.v1.BrokerService/FetchRetained"
	BrokerService_FetchWill_FullMethodName           = "/fluxmq.cluster.v1.BrokerService/FetchWill"
	BrokerService_EnqueueRemote_FullMethodName       = "/fluxmq.cluster.v1.BrokerService/EnqueueRemote"
	BrokerService_RouteQueueMessage_FullMethodName   = "/fluxmq.cluster.v1.BrokerService/RouteQueueMessage"
	BrokerService_RouteQueueBatch_FullMethodName     = "/fluxmq.cluster.v1.BrokerService/RouteQueueBatch"
	BrokerService_AppendEntries_FullMethodName       = "/fluxmq.cluster.v1.BrokerService/AppendEntries"
	BrokerService_RequestVote_FullMethodName         = "/fluxmq.cluster.v1.BrokerService/RequestVote"
	BrokerService_InstallSnapshot_FullMethodName     = "/fluxmq.cluster.v1.BrokerService/InstallSnapshot"
	BrokerService_ForwardGroupOp_FullMethodName      = "/fluxmq.cluster.v1.BrokerService/ForwardGroupOp"
	BrokerService_ForwardPublishBatch_FullMethodName = "/fluxmq.cluster.v1.BrokerService/ForwardPublishBatch"
)

// BrokerServiceClient is the client API for BrokerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BrokerService defines RPC methods for inter-broker communication in the cluster.
// This is an internal API not exposed to clients.
type BrokerServiceClient interface {
	// RoutePublish forwards a PUBLISH packet to the broker that owns the target session.
	RoutePublish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error)
	// RoutePublishBatch forwards multiple PUBLISH packets in one RPC.
	RoutePublishBatch(ctx context.Context, in *PublishBatchRequest, opts ...grpc.CallOption) (*PublishBatchResponse, error)
	// TakeoverSession migrates a session from one broker to another.
	TakeoverSession(ctx context.Context, in *TakeoverRequest, opts ...grpc.CallOption) (*TakeoverResponse, error)
	// FetchRetained fetches a retained message payload from the owning broker node.
	FetchRetained(ctx context.Context, in *FetchRetainedRequest, opts ...grpc.CallOption) (*FetchRetainedResponse, error)
	// FetchWill fetches a will message payload from the owning broker node.
	FetchWill(ctx context.Context, in *FetchWillRequest, opts ...grpc.CallOption) (*FetchWillResponse, error)
	// EnqueueRemote routes an enqueue operation to the remote node.
	EnqueueRemote(ctx context.Context, in *EnqueueRemoteRequest, opts ...grpc.CallOption) (*EnqueueRemoteResponse, error)
	// RouteQueueMessage delivers a queue message to a consumer on a different node.
	RouteQueueMessage(ctx context.Context, in *RouteQueueMessageRequest, opts ...grpc.CallOption) (*RouteQueueMessageResponse, error)
	// RouteQueueBatch delivers multiple queue messages in one RPC.
	RouteQueueBatch(ctx context.Context, in *RouteQueueBatchRequest, opts ...grpc.CallOption) (*RouteQueueBatchResponse, error)
	// AppendEntries is invoked by the Raft leader to replicate log entries.
	AppendEntries(ctx context.Context, in *AppendEntriesRequest, opts ...grpc.CallOption) (*AppendEntriesResponse, error)
	// RequestVote is invoked by candidates during leader election.
	RequestVote(ctx context.Context, in *RequestVoteRequest, opts ...grpc.CallOption) (*RequestVoteResponse, error)
	// InstallSnapshot is invoked by leader to transfer snapshot to a follower.
	InstallSnapshot(ctx context.Context, in *InstallSnapshotRequest, opts ...grpc.CallOption) (*InstallSnapshotResponse, error)
	// ForwardGroupOp forwards a consumer group mutation from a follower to the
	// Raft leader for the queue's replication group. The leader applies the
	// operation through its coordinator so it goes through Raft consensus.
	ForwardGroupOp(ctx context.Context, in *ForwardGroupOpRequest, opts ...grpc.CallOption) (*ForwardGroupOpResponse, error)
	// ForwardPublishBatch forwards messages to a node for local fan-out.
	// The receiving node matches its own local subscriptions and delivers.
	// This replaces per-subscriber routing with per-node routing.
	ForwardPublishBatch(ctx context.Context, in *ForwardPublishBatchRequest, opts ...grpc.CallOption) (*ForwardPublishBatchResponse, error)
}

type brokerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBrokerServiceClient(cc grpc.ClientConnInterface) BrokerServiceClient {
	return &brokerServiceClient{cc}
}

func (c *brokerServiceClient) RoutePublish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishResponse)
	err := c.cc.Invoke(ctx, BrokerService_RoutePublish_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerServiceClient) RoutePublishBatch(ctx context.Context, in *PublishBatchRequest, opts ...grpc.CallOption) (*PublishBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishBatchResponse)
	err := c.cc.Invoke(ctx, BrokerService_RoutePublishBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerServiceClient) TakeoverSession(ctx context.Context, in *TakeoverRequest, opts ...grpc.CallOption) (*TakeoverResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TakeoverResponse)
	err := c.cc.Invoke(ctx, BrokerService_TakeoverSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerServiceClient) FetchRetained(ctx context.Context, in *FetchRetainedRequest, opts ...grpc.CallOption) (*FetchRetainedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchRetainedResponse)
	err := c.cc.Invoke(ctx, BrokerService_FetchRetained_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerServiceClient) FetchWill(ctx context.Context, in *FetchWillRequest, opts ...grpc.CallOption) (*FetchWillResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchWillResponse)
	err := c.cc.Invoke(ctx, BrokerService_FetchWill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerServiceClient) EnqueueRemote(ctx context.Context, in *EnqueueRemoteRequest, opts ...grpc.CallOption) (*EnqueueRemoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnqueueRemoteResponse)
	err := c.cc.Invoke(ctx, BrokerService_EnqueueRemote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerServiceClient) RouteQueueMessage(ctx context.Context, in *RouteQueueMessageRequest, opts ...grpc.CallOption) (*RouteQueueMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RouteQueueMessageResponse)
	err := c.cc.Invoke(ctx, BrokerService_RouteQueueMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerServiceClient) RouteQueueBatch(ctx context.Context, in *RouteQueueBatchRequest, opts ...grpc.CallOption) (*RouteQueueBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RouteQueueBatchResponse)
	err := c.cc.Invoke(ctx, BrokerService_RouteQueueBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerServiceClient) AppendEntries(ctx context.Context, in *AppendEntriesRequest, opts ...grpc.CallOption) (*AppendEntriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppendEntriesResponse)
	err := c.cc.Invoke(ctx, BrokerService_AppendEntries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerServiceClient) RequestVote(ctx context.Context, in *RequestVoteRequest, opts ...grpc.CallOption) (*RequestVoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestVoteResponse)
	err := c.cc.Invoke(ctx, BrokerService_RequestVote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerServiceClient) InstallSnapshot(ctx context.Context, in *InstallSnapshotRequest, opts ...grpc.CallOption) (*InstallSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstallSnapshotResponse)
	err := c.cc.Invoke(ctx, BrokerService_InstallSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerServiceClient) ForwardGroupOp(ctx context.Context, in *ForwardGroupOpRequest, opts ...grpc.CallOption) (*ForwardGroupOpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForwardGroupOpResponse)
	err := c.cc.Invoke(ctx, BrokerService_ForwardGroupOp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerServiceClient) ForwardPublishBatch(ctx context.Context, in *ForwardPublishBatchRequest, opts ...grpc.CallOption) (*ForwardPublishBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForwardPublishBatchResponse)
	err := c.cc.Invoke(ctx, BrokerService_ForwardPublishBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BrokerServiceServer is the server API for BrokerService service.
// All implementations must embed UnimplementedBrokerServiceServer
// for forward compatibility.
//
// BrokerService defines RPC methods for inter-broker communication in the cluster.
// This is an internal API not exposed to clients.
type BrokerServiceServer interface {
	// RoutePublish forwards a PUBLISH packet to the broker that owns the target session.
	RoutePublish(context.Context, *PublishRequest) (*PublishResponse, error)
	// RoutePublishBatch forwards multiple PUBLISH packets in one RPC.
	RoutePublishBatch(context.Context, *PublishBatchRequest) (*PublishBatchResponse, error)
	// TakeoverSession migrates a session from one broker to another.
	TakeoverSession(context.Context, *TakeoverRequest) (*TakeoverResponse, error)
	// FetchRetained fetches a retained message payload from the owning broker node.
	FetchRetained(context.Context, *FetchRetainedRequest) (*FetchRetainedResponse, error)
	// FetchWill fetches a will message payload from the owning broker node.
	FetchWill(context.Context, *FetchWillRequest) (*FetchWillResponse, error)
	// EnqueueRemote routes an enqueue operation to the remote node.
	EnqueueRemote(context.Context, *EnqueueRemoteRequest) (*EnqueueRemoteResponse, error)
	// RouteQueueMessage delivers a queue message to a consumer on a different node.
	RouteQueueMessage(context.Context, *RouteQueueMessageRequest) (*RouteQueueMessageResponse, error)
	// RouteQueueBatch delivers multiple queue messages in one RPC.
	RouteQueueBatch(context.Context, *RouteQueueBatchRequest) (*RouteQueueBatchResponse, error)
	// AppendEntries is invoked by the Raft leader to replicate log entries.
	AppendEntries(context.Context, *AppendEntriesRequest) (*AppendEntriesResponse, error)
	// RequestVote is invoked by candidates during leader election.
	RequestVote(context.Context, *RequestVoteRequest) (*RequestVoteResponse, error)
	// InstallSnapshot is invoked by leader to transfer snapshot to a follower.
	InstallSnapshot(context.Context, *InstallSnapshotRequest) (*InstallSnapshotResponse, error)
	// ForwardGroupOp forwards a consumer group mutation from a follower to the
	// Raft leader for the queue's replication group. The leader applies the
	// operation through its coordinator so it goes through Raft consensus.
	ForwardGroupOp(context.Context, *ForwardGroupOpRequest) (*ForwardGroupOpResponse, error)
	// ForwardPublishBatch forwards messages to a node for local fan-out.
	// The receiving node matches its own local subscriptions and delivers.
	// This replaces per-subscriber routing with per-node routing.
	ForwardPublishBatch(context.Context, *ForwardPublishBatchRequest) (*ForwardPublishBatchResponse, error)
	mustEmbedUnimplementedBrokerServiceServer()
}

// UnimplementedBrokerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBrokerServiceServer struct{}

func (UnimplementedBrokerServiceServer) RoutePublish(context.Context, *PublishRequest) (*PublishResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RoutePublish not implemented")
}

func (UnimplementedBrokerServiceServer) RoutePublishBatch(context.Context, *PublishBatchRequest) (*PublishBatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RoutePublishBatch not implemented")
}

func (UnimplementedBrokerServiceServer) TakeoverSession(context.Context, *TakeoverRequest) (*TakeoverResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TakeoverSession not implemented")
}

func (UnimplementedBrokerServiceServer) FetchRetained(context.Context, *FetchRetainedRequest) (*FetchRetainedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchRetained not implemented")
}

func (UnimplementedBrokerServiceServer) FetchWill(context.Context, *FetchWillRequest) (*FetchWillResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchWill not implemented")
}

func (UnimplementedBrokerServiceServer) EnqueueRemote(context.Context, *EnqueueRemoteRequest) (*EnqueueRemoteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnqueueRemote not implemented")
}

func (UnimplementedBrokerServiceServer) RouteQueueMessage(context.Context, *RouteQueueMessageRequest) (*RouteQueueMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RouteQueueMessage not implemented")
}

func (UnimplementedBrokerServiceServer) RouteQueueBatch(context.Context, *RouteQueueBatchRequest) (*RouteQueueBatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RouteQueueBatch not implemented")
}

func (UnimplementedBrokerServiceServer) AppendEntries(context.Context, *AppendEntriesRequest) (*AppendEntriesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AppendEntries not implemented")
}

func (UnimplementedBrokerServiceServer) RequestVote(context.Context, *RequestVoteRequest) (*RequestVoteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestVote not implemented")
}

func (UnimplementedBrokerServiceServer) InstallSnapshot(context.Context, *InstallSnapshotRequest) (*InstallSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InstallSnapshot not implemented")
}

func (UnimplementedBrokerServiceServer) ForwardGroupOp(context.Context, *ForwardGroupOpRequest) (*ForwardGroupOpResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ForwardGroupOp not implemented")
}

func (UnimplementedBrokerServiceServer) ForwardPublishBatch(context.Context, *ForwardPublishBatchRequest) (*ForwardPublishBatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ForwardPublishBatch not implemented")
}
func (UnimplementedBrokerServiceServer) mustEmbedUnimplementedBrokerServiceServer() {}
func (UnimplementedBrokerServiceServer) testEmbeddedByValue()                       {}

// UnsafeBrokerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BrokerServiceServer will
// result in compilation errors.
type UnsafeBrokerServiceServer interface {
	mustEmbedUnimplementedBrokerServiceServer()
}

func RegisterBrokerServiceServer(s grpc.ServiceRegistrar, srv BrokerServiceServer) {
	// If the following call panics, it indicates UnimplementedBrokerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BrokerService_ServiceDesc, srv)
}

func _BrokerService_RoutePublish_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(PublishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServiceServer).RoutePublish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrokerService_RoutePublish_FullMethodName,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(BrokerServiceServer).RoutePublish(ctx, req.(*PublishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerService_RoutePublishBatch_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(PublishBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServiceServer).RoutePublishBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrokerService_RoutePublishBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(BrokerServiceServer).RoutePublishBatch(ctx, req.(*PublishBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerService_TakeoverSession_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(TakeoverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServiceServer).TakeoverSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrokerService_TakeoverSession_FullMethodName,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(BrokerServiceServer).TakeoverSession(ctx, req.(*TakeoverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerService_FetchRetained_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(FetchRetainedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServiceServer).FetchRetained(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrokerService_FetchRetained_FullMethodName,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(BrokerServiceServer).FetchRetained(ctx, req.(*FetchRetainedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerService_FetchWill_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(FetchWillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServiceServer).FetchWill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrokerService_FetchWill_FullMethodName,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(BrokerServiceServer).FetchWill(ctx, req.(*FetchWillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerService_EnqueueRemote_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(EnqueueRemoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServiceServer).EnqueueRemote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrokerService_EnqueueRemote_FullMethodName,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(BrokerServiceServer).EnqueueRemote(ctx, req.(*EnqueueRemoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerService_RouteQueueMessage_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(RouteQueueMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServiceServer).RouteQueueMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrokerService_RouteQueueMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(BrokerServiceServer).RouteQueueMessage(ctx, req.(*RouteQueueMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerService_RouteQueueBatch_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(RouteQueueBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServiceServer).RouteQueueBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrokerService_RouteQueueBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(BrokerServiceServer).RouteQueueBatch(ctx, req.(*RouteQueueBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerService_AppendEntries_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(AppendEntriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServiceServer).AppendEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrokerService_AppendEntries_FullMethodName,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(BrokerServiceServer).AppendEntries(ctx, req.(*AppendEntriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerService_RequestVote_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(RequestVoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServiceServer).RequestVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrokerService_RequestVote_FullMethodName,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(BrokerServiceServer).RequestVote(ctx, req.(*RequestVoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerService_InstallSnapshot_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(InstallSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServiceServer).InstallSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrokerService_InstallSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(BrokerServiceServer).InstallSnapshot(ctx, req.(*InstallSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerService_ForwardGroupOp_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(ForwardGroupOpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServiceServer).ForwardGroupOp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrokerService_ForwardGroupOp_FullMethodName,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(BrokerServiceServer).ForwardGroupOp(ctx, req.(*ForwardGroupOpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerService_ForwardPublishBatch_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(ForwardPublishBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServiceServer).ForwardPublishBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrokerService_ForwardPublishBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(BrokerServiceServer).ForwardPublishBatch(ctx, req.(*ForwardPublishBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BrokerService_ServiceDesc is the grpc.ServiceDesc for BrokerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BrokerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fluxmq.cluster.v1.BrokerService",
	HandlerType: (*BrokerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RoutePublish",
			Handler:    _BrokerService_RoutePublish_Handler,
		},
		{
			MethodName: "RoutePublishBatch",
			Handler:    _BrokerService_RoutePublishBatch_Handler,
		},
		{
			MethodName: "TakeoverSession",
			Handler:    _BrokerService_TakeoverSession_Handler,
		},
		{
			MethodName: "FetchRetained",
			Handler:    _BrokerService_FetchRetained_Handler,
		},
		{
			MethodName: "FetchWill",
			Handler:    _BrokerService_FetchWill_Handler,
		},
		{
			MethodName: "EnqueueRemote",
			Handler:    _BrokerService_EnqueueRemote_Handler,
		},
		{
			MethodName: "RouteQueueMessage",
			Handler:    _BrokerService_RouteQueueMessage_Handler,
		},
		{
			MethodName: "RouteQueueBatch",
			Handler:    _BrokerService_RouteQueueBatch_Handler,
		},
		{
			MethodName: "AppendEntries",
			Handler:    _BrokerService_AppendEntries_Handler,
		},
		{
			MethodName: "RequestVote",
			Handler:    _BrokerService_RequestVote_Handler,
		},
		{
			MethodName: "InstallSnapshot",
			Handler:    _BrokerService_InstallSnapshot_Handler,
		},
		{
			MethodName: "ForwardGroupOp",
			Handler:    _BrokerService_ForwardGroupOp_Handler,
		},
		{
			MethodName: "ForwardPublishBatch",
			Handler:    _BrokerService_ForwardPublishBatch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cluster/v1/broker.proto",
}
