// Copyright (c) Abstract Machines
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: cluster/v1/broker.proto

package clusterv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Qos           uint32                 `protobuf:"varint,4,opt,name=qos,proto3" json:"qos,omitempty"`
	Retain        bool                   `protobuf:"varint,5,opt,name=retain,proto3" json:"retain,omitempty"`
	Dup           bool                   `protobuf:"varint,6,opt,name=dup,proto3" json:"dup,omitempty"`
	Properties    map[string]string      `protobuf:"bytes,7,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_cluster_v1_broker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_broker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_cluster_v1_broker_proto_rawDescGZIP(), []int{0}
}

func (x *PublishRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *PublishRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *PublishRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PublishRequest) GetQos() uint32 {
	if x != nil {
		return x.Qos
	}
	return 0
}

func (x *PublishRequest) GetRetain() bool {
	if x != nil {
		return x.Retain
	}
	return false
}

func (x *PublishRequest) GetDup() bool {
	if x != nil {
		return x.Dup
	}
	return false
}

func (x *PublishRequest) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

type PublishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	mi := &file_cluster_v1_broker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_broker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_cluster_v1_broker_proto_rawDescGZIP(), []int{1}
}

func (x *PublishResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PublishResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type PublishBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*PublishRequest      `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishBatchRequest) Reset() {
	*x = PublishBatchRequest{}
	mi := &file_cluster_v1_broker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishBatchRequest) ProtoMessage() {}

func (x *PublishBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_broker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishBatchRequest.ProtoReflect.Descriptor instead.
func (*PublishBatchRequest) Descriptor() ([]byte, []int) {
	return file_cluster_v1_broker_proto_rawDescGZIP(), []int{2}
}

func (x *PublishBatchRequest) GetMessages() []*PublishRequest {
	if x != nil {
		return x.Messages
	}
	return nil
}

type PublishBatchError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint32                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishBatchError) Reset() {
	*x = PublishBatchError{}
	mi := &file_cluster_v1_broker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishBatchError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishBatchError) ProtoMessage() {}

func (x *PublishBatchError) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_broker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishBatchError.ProtoReflect.Descriptor instead.
func (*PublishBatchError) Descriptor() ([]byte, []int) {
	return file_cluster_v1_broker_proto_rawDescGZIP(), []int{3}
}

func (x *PublishBatchError) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *PublishBatchError) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *PublishBatchError) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type PublishBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Delivered     uint32                 `protobuf:"varint,3,opt,name=delivered,proto3" json:"delivered,omitempty"`
	Failures      []*PublishBatchError   `protobuf:"bytes,4,rep,name=failures,proto3" json:"failures,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishBatchResponse) Reset() {
	*x = PublishBatchResponse{}
	mi := &file_cluster_v1_broker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishBatchResponse) ProtoMessage() {}

func (x *PublishBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_broker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishBatchResponse.ProtoReflect.Descriptor instead.
func (*PublishBatchResponse) Descriptor() ([]byte, []int) {
	return file_cluster_v1_broker_proto_rawDescGZIP(), []int{4}
}

func (x *PublishBatchResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PublishBatchResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *PublishBatchResponse) GetDelivered() uint32 {
	if x != nil {
		return x.Delivered
	}
	return 0
}

func (x *PublishBatchResponse) GetFailures() []*PublishBatchError {
	if x != nil {
		return x.Failures
	}
	return nil
}

type TakeoverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	FromNode      string                 `protobuf:"bytes,2,opt,name=from_node,json=fromNode,proto3" json:"from_node,omitempty"`
	ToNode        string                 `protobuf:"bytes,3,opt,name=to_node,json=toNode,proto3" json:"to_node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TakeoverRequest) Reset() {
	*x = TakeoverRequest{}
	mi := &file_cluster_v1_broker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TakeoverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TakeoverRequest) ProtoMessage() {}

func (x *TakeoverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_broker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TakeoverRequest.ProtoReflect.Descriptor instead.
func (*TakeoverRequest) Descriptor() ([]byte, []int) {
	return file_cluster_v1_broker_proto_rawDescGZIP(), []int{5}
}

func (x *TakeoverRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *TakeoverRequest) GetFromNode() string {
	if x != nil {
		return x.FromNode
	}
	return ""
}

func (x *TakeoverRequest) GetToNode() string {
	if x != nil {
		return x.ToNode
	}
	return ""
}

type TakeoverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	SessionState  *SessionState          `protobuf:"bytes,3,opt,name=session_state,json=sessionState,proto3" json:"session_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TakeoverResponse) Reset() {
	*x = TakeoverResponse{}
	mi := &file_cluster_v1_broker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TakeoverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TakeoverResponse) ProtoMessage() {}

func (x *TakeoverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_broker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TakeoverResponse.ProtoReflect.Descriptor instead.
func (*TakeoverResponse) Descriptor() ([]byte, []int) {
	return file_cluster_v1_broker_proto_rawDescGZIP(), []int{6}
}

func (x *TakeoverResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TakeoverResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *TakeoverResponse) GetSessionState() *SessionState {
	if x != nil {
		return x.SessionState
	}
	return nil
}

type SessionState struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ExpiryInterval   uint32                 `protobuf:"varint,1,opt,name=expiry_interval,json=expiryInterval,proto3" json:"expiry_interval,omitempty"`
	CleanStart       bool                   `protobuf:"varint,2,opt,name=clean_start,json=cleanStart,proto3" json:"clean_start,omitempty"`
	InflightMessages []*InflightMessage     `protobuf:"bytes,3,rep,name=inflight_messages,json=inflightMessages,proto3" json:"inflight_messages,omitempty"`
	QueuedMessages   []*QueuedMessage       `protobuf:"bytes,4,rep,name=queued_messages,json=queuedMessages,proto3" json:"queued_messages,omitempty"`
	Subscriptions    []*Subscription        `protobuf:"bytes,5,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	Will             *WillMessage           `protobuf:"bytes,6,opt,name=will,proto3" json:"will,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SessionState) Reset() {
	*x = SessionState{}
	mi := &file_cluster_v1_broker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionState) ProtoMessage() {}

func (x *SessionState) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_broker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionState.ProtoReflect.Descriptor instead.
func (*SessionState) Descriptor() ([]byte, []int) {
	return file_cluster_v1_broker_proto_rawDescGZIP(), []int{7}
}

func (x *SessionState) GetExpiryInterval() uint32 {
	if x != nil {
		return x.ExpiryInterval
	}
	return 0
}

func (x *SessionState) GetCleanStart() bool {
	if x != nil {
		return x.CleanStart
	}
	return false
}

func (x *SessionState) GetInflightMessages() []*InflightMessage {
	if x != nil {
		return x.InflightMessages
	}
	return nil
}

func (x *SessionState) GetQueuedMessages() []*QueuedMessage {
	if x != nil {
		return x.QueuedMessages
	}
	return nil
}

func (x *SessionState) GetSubscriptions() []*Subscription {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

func (x *SessionState) GetWill() *WillMessage {
	if x != nil {
		return x.Will
	}
	return nil
}

type InflightMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PacketId      uint32                 `protobuf:"varint,1,opt,name=packet_id,json=packetId,proto3" json:"packet_id,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Qos           uint32                 `protobuf:"varint,4,opt,name=qos,proto3" json:"qos,omitempty"`
	Retain        bool                   `protobuf:"varint,5,opt,name=retain,proto3" json:"retain,omitempty"`
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InflightMessage) Reset() {
	*x = InflightMessage{}
	mi := &file_cluster_v1_broker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InflightMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InflightMessage) ProtoMessage() {}

func (x *InflightMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_broker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InflightMessage.ProtoReflect.Descriptor instead.
func (*InflightMessage) Descriptor() ([]byte, []int) {
	return file_cluster_v1_broker_proto_rawDescGZIP(), []int{8}
}

func (x *InflightMessage) GetPacketId() uint32 {
	if x != nil {
		return x.PacketId
	}
	return 0
}

func (x *InflightMessage) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *InflightMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *InflightMessage) GetQos() uint32 {
	if x != nil {
		return x.Qos
	}
	return 0
}

func (x *InflightMessage) GetRetain() bool {
	if x != nil {
		return x.Retain
	}
	return false
}

func (x *InflightMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type QueuedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Qos           uint32                 `protobuf:"varint,3,opt,name=qos,proto3" json:"qos,omitempty"`
	Retain        bool                   `protobuf:"varint,4,opt,name=retain,proto3" json:"retain,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueuedMessage) Reset() {
	*x = QueuedMessage{}
	mi := &file_cluster_v1_broker_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueuedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueuedMessage) ProtoMessage() {}

func (x *QueuedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_broker_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueuedMessage.ProtoReflect.Descriptor instead.
func (*QueuedMessage) Descriptor() ([]byte, []int) {
	return file_cluster_v1_broker_proto_rawDescGZIP(), []int{9}
}

func (x *QueuedMessage) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *QueuedMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *QueuedMessage) GetQos() uint32 {
	if x != nil {
		return x.Qos
	}
	return 0
}

func (x *QueuedMessage) GetRetain() bool {
	if x != nil {
		return x.Retain
	}
	return false
}

func (x *QueuedMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type Subscription struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        string                 `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	Qos           uint32                 `protobuf:"varint,2,opt,name=qos,proto3" json:"qos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscription) Reset() {
	*x = Subscription{}
	mi := &file_cluster_v1_broker_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscription) ProtoMessage() {}

func (x *Subscription) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_broker_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscription.ProtoReflect.Descriptor instead.
func (*Subscription) Descriptor() ([]byte, []int) {
	return file_cluster_v1_broker_proto_rawDescGZIP(), []int{10}
}

func (x *Subscription) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *Subscription) GetQos() uint32 {
	if x != nil {
		return x.Qos
	}
	return 0
}

type WillMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Topic          string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Payload        []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Qos            uint32                 `protobuf:"varint,3,opt,name=qos,proto3" json:"qos,omitempty"`
	Retain         bool                   `protobuf:"varint,4,opt,name=retain,proto3" json:"retain,omitempty"`
	Delay          uint32                 `protobuf:"varint,5,opt,name=delay,proto3" json:"delay,omitempty"`
	DisconnectTime int64                  `protobuf:"varint,6,opt,name=disconnect_time,json=disconnectTime,proto3" json:"disconnect_time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WillMessage) Reset() {
	*x = WillMessage{}
	mi := &file_cluster_v1_broker_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WillMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WillMessage) ProtoMessage() {}

func (x *WillMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_broker_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WillMessage.ProtoReflect.Descriptor instead.
func (*WillMessage) Descriptor() ([]byte, []int) {
	return file_cluster_v1_broker_proto_rawDescGZIP(), []int{11}
}

func (x *WillMessage) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *WillMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WillMessage) GetQos() uint32 {
	if x != nil {
		return x.Qos
	}
	return 0
}

func (x *WillMessage) GetRetain() bool {
	if x != nil {
		return x.Retain
	}
	return false
}

func (x *WillMessage) GetDelay() uint32 {
	if x != nil {
		return x.Delay
	}
	return 0
}

func (x *WillMessage) GetDisconnectTime() int64 {
	if x != nil {
		return x.DisconnectTime
	}
	return 0
}

type FetchRetainedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchRetainedRequest) Reset() {
	*x = FetchRetainedRequest{}
	mi := &file_cluster_v1_broker_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchRetainedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchRetainedRequest) ProtoMessage() {}

func (x *FetchRetainedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_broker_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchRetainedRequest.ProtoReflect.Descriptor instead.
func (*FetchRetainedRequest) Descriptor() ([]byte, []int) {
	return file_cluster_v1_broker_proto_rawDescGZIP(), []int{12}
}

func (x *FetchRetainedRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type FetchRetainedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Message       *RetainedMessage       `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchRetainedResponse) Reset() {
	*x = FetchRetainedResponse{}
	mi := &file_cluster_v1_broker_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchRetainedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchRetainedResponse) ProtoMessage() {}

func (x *FetchRetainedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_broker_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchRetainedResponse.ProtoReflect.Descriptor instead.
func (*FetchRetainedResponse) Descriptor() ([]byte, []int) {
	return file_cluster_v1_broker_proto_rawDescGZIP(), []int{13}
}

func (x *FetchRetainedResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *FetchRetainedResponse) GetMessage() *RetainedMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *FetchRetainedResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RetainedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Qos           uint32                 `protobuf:"varint,3,opt,name=qos,proto3" json:"qos,omitempty"`
	Retain        bool                   `protobuf:"varint,4,opt,name=retain,proto3" json:"retain,omitempty"`
	Properties    map[string]string      `protobuf:"bytes,5,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetainedMessage) Reset() {
	*x = RetainedMessage{}
	mi := &file_cluster_v1_broker_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetainedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetainedMessage) ProtoMessage() {}

func (x *RetainedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_broker_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetainedMessage.ProtoReflect.Descriptor instead.
func (*RetainedMessage) Descriptor() ([]byte, []int) {
	return file_cluster_v1_broker_proto_rawDescGZIP(), []int{14}
}

func (x *RetainedMessage) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *RetainedMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RetainedMessage) GetQos() uint32 {
	if x != nil {
		return x.Qos
	}
	return 0
}

func (x *RetainedMessage) GetRetain() bool {
	if x != nil {
		return x.Retain
	}
	return false
}

func (x *RetainedMessage) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *RetainedMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type FetchWillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchWillRequest) Reset() {
	*x = FetchWillRequest{}
	mi := &file_cluster_v1_broker_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchWillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchWillRequest) ProtoMessage() {}

func (x *FetchWillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_broker_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchWillRequest.ProtoReflect.Descriptor instead.
func (*FetchWillRequest) Descriptor() ([]byte, []int) {
	return file_cluster_v1_broker_proto_rawDescGZIP(), []int{15}
}

func (x *FetchWillRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type FetchWillResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Message       *WillMessage           `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchWillResponse) Reset() {
	*x = FetchWillResponse{}
	mi := &file_cluster_v1_broker_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchWillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchWillResponse) ProtoMessage() {}

func (x *FetchWillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_broker_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchWillResponse.ProtoReflect.Descriptor instead.
func (*FetchWillResponse) Descriptor() ([]byte, []int) {
	return file_cluster_v1_broker_proto_rawDescGZIP(), []int{16}
}

func (x *FetchWillResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *FetchWillResponse) GetMessage() *WillMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *FetchWillResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type EnqueueRemoteRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	QueueName        string                 `protobuf:"bytes,1,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	Payload          []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Properties       map[string]string      `protobuf:"bytes,3,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ForwardedPublish bool                   `protobuf:"varint,4,opt,name=forwarded_publish,json=forwardedPublish,proto3" json:"forwarded_publish,omitempty"`
	ForwardToLeader  bool                   `protobuf:"varint,5,opt,name=forward_to_leader,json=forwardToLeader,proto3" json:"forward_to_leader,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EnqueueRemoteRequest) Reset() {
	*x = EnqueueRemoteRequest{}
	mi := &file_cluster_v1_broker_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueRemoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueRemoteRequest) ProtoMessage() {}

func (x *EnqueueRemoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_broker_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueRemoteRequest.ProtoReflect.Descriptor instead.
func (*EnqueueRemoteRequest) Descriptor() ([]byte, []int) {
	return file_cluster_v1_broker_proto_rawDescGZIP(), []int{17}
}

func (x *EnqueueRemoteRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *EnqueueRemoteRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *EnqueueRemoteRequest) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *EnqueueRemoteRequest) GetForwardedPublish() bool {
	if x != nil {
		return x.ForwardedPublish
	}
	return false
}

func (x *EnqueueRemoteRequest) GetForwardToLeader() bool {
	if x != nil {
		return x.ForwardToLeader
	}
	return false
}

type EnqueueRemoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	MessageId     string                 `protobuf:"bytes,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueRemoteResponse) Reset() {
	*x = EnqueueRemoteResponse{}
	mi := &file_cluster_v1_broker_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueRemoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueRemoteResponse) ProtoMessage() {}

func (x *EnqueueRemoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_broker_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueRemoteResponse.ProtoReflect.Descriptor instead.
func (*EnqueueRemoteResponse) Descriptor() ([]byte, []int) {
	return file_cluster_v1_broker_proto_rawDescGZIP(), []int{18}
}

func (x *EnqueueRemoteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EnqueueRemoteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *EnqueueRemoteResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type RouteQueueMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	QueueName     string                 `protobuf:"bytes,2,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	MessageId     string                 `protobuf:"bytes,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	Properties    map[string]string      `protobuf:"bytes,5,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Sequence      int64                  `protobuf:"varint,6,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteQueueMessageRequest) Reset() {
	*x = RouteQueueMessageRequest{}
	mi := &file_cluster_v1_broker_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteQueueMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteQueueMessageRequest) ProtoMessage() {}

func (x *RouteQueueMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_broker_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteQueueMessageRequest.ProtoReflect.Descriptor instead.
func (*RouteQueueMessageRequest) Descriptor() ([]byte, []int) {
	return file_cluster_v1_broker_proto_rawDescGZIP(), []int{19}
}

func (x *RouteQueueMessageRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *RouteQueueMessageRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *RouteQueueMessageRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *RouteQueueMessageRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RouteQueueMessageRequest) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *RouteQueueMessageRequest) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

type RouteQueueMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteQueueMessageResponse) Reset() {
	*x = RouteQueueMessageResponse{}
	mi := &file_cluster_v1_broker_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteQueueMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteQueueMessageResponse) ProtoMessage() {}

func (x *RouteQueueMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_broker_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteQueueMessageResponse.ProtoReflect.Descriptor instead.
func (*RouteQueueMessageResponse) Descriptor() ([]byte, []int) {
	return file_cluster_v1_broker_proto_rawDescGZIP(), []int{20}
}

func (x *RouteQueueMessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RouteQueueMessageResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RouteQueueBatchRequest struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Messages      []*RouteQueueMessageRequest `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteQueueBatchRequest) Reset() {
	*x = RouteQueueBatchRequest{}
	mi := &file_cluster_v1_broker_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteQueueBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteQueueBatchRequest) ProtoMessage() {}

func (x *RouteQueueBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_broker_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteQueueBatchRequest.ProtoReflect.Descriptor instead.
func (*RouteQueueBatchRequest) Descriptor() ([]byte, []int) {
	return file_cluster_v1_broker_proto_rawDescGZIP(), []int{21}
}

func (x *RouteQueueBatchRequest) GetMessages() []*RouteQueueMessageRequest {
	if x != nil {
		return x.Messages
	}
	return nil
}

type RouteQueueBatchError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint32                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	QueueName     string                 `protobuf:"bytes,3,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteQueueBatchError) Reset() {
	*x = RouteQueueBatchError{}
	mi := &file_cluster_v1_broker_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteQueueBatchError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteQueueBatchError) ProtoMessage() {}

func (x *RouteQueueBatchError) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_broker_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteQueueBatchError.ProtoReflect.Descriptor instead.
func (*RouteQueueBatchError) Descriptor() ([]byte, []int) {
	return file_cluster_v1_broker_proto_rawDescGZIP(), []int{22}
}

func (x *RouteQueueBatchError) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *RouteQueueBatchError) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *RouteQueueBatchError) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *RouteQueueBatchError) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RouteQueueBatchResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Success       bool                    `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                  `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Delivered     uint32                  `protobuf:"varint,3,opt,name=delivered,proto3" json:"delivered,omitempty"`
	Failures      []*RouteQueueBatchError `protobuf:"bytes,4,rep,name=failures,proto3" json:"failures,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteQueueBatchResponse) Reset() {
	*x = RouteQueueBatchResponse{}
	mi := &file_cluster_v1_broker_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteQueueBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteQueueBatchResponse) ProtoMessage() {}

func (x *RouteQueueBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_broker_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteQueueBatchResponse.ProtoReflect.Descriptor instead.
func (*RouteQueueBatchResponse) Descriptor() ([]byte, []int) {
	return file_cluster_v1_broker_proto_rawDescGZIP(), []int{23}
}

func (x *RouteQueueBatchResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RouteQueueBatchResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RouteQueueBatchResponse) GetDelivered() uint32 {
	if x != nil {
		return x.Delivered
	}
	return 0
}

func (x *RouteQueueBatchResponse) GetFailures() []*RouteQueueBatchError {
	if x != nil {
		return x.Failures
	}
	return nil
}

type AppendEntriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueueName     string                 `protobuf:"bytes,1,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	Term          uint64                 `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	LeaderId      string                 `protobuf:"bytes,3,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	PrevLogIndex  uint64                 `protobuf:"varint,4,opt,name=prev_log_index,json=prevLogIndex,proto3" json:"prev_log_index,omitempty"`
	PrevLogTerm   uint64                 `protobuf:"varint,5,opt,name=prev_log_term,json=prevLogTerm,proto3" json:"prev_log_term,omitempty"`
	Entries       [][]byte               `protobuf:"bytes,6,rep,name=entries,proto3" json:"entries,omitempty"`
	LeaderCommit  uint64                 `protobuf:"varint,7,opt,name=leader_commit,json=leaderCommit,proto3" json:"leader_commit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendEntriesRequest) Reset() {
	*x = AppendEntriesRequest{}
	mi := &file_cluster_v1_broker_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEntriesRequest) ProtoMessage() {}

func (x *AppendEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_broker_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEntriesRequest.ProtoReflect.Descriptor instead.
func (*AppendEntriesRequest) Descriptor() ([]byte, []int) {
	return file_cluster_v1_broker_proto_rawDescGZIP(), []int{24}
}

func (x *AppendEntriesRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *AppendEntriesRequest) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *AppendEntriesRequest) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

func (x *AppendEntriesRequest) GetPrevLogIndex() uint64 {
	if x != nil {
		return x.PrevLogIndex
	}
	return 0
}

func (x *AppendEntriesRequest) GetPrevLogTerm() uint64 {
	if x != nil {
		return x.PrevLogTerm
	}
	return 0
}

func (x *AppendEntriesRequest) GetEntries() [][]byte {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *AppendEntriesRequest) GetLeaderCommit() uint64 {
	if x != nil {
		return x.LeaderCommit
	}
	return 0
}

type AppendEntriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          uint64                 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	LastLogIndex  uint64                 `protobuf:"varint,3,opt,name=last_log_index,json=lastLogIndex,proto3" json:"last_log_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendEntriesResponse) Reset() {
	*x = AppendEntriesResponse{}
	mi := &file_cluster_v1_broker_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEntriesResponse) ProtoMessage() {}

func (x *AppendEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_broker_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEntriesResponse.ProtoReflect.Descriptor instead.
func (*AppendEntriesResponse) Descriptor() ([]byte, []int) {
	return file_cluster_v1_broker_proto_rawDescGZIP(), []int{25}
}

func (x *AppendEntriesResponse) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *AppendEntriesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AppendEntriesResponse) GetLastLogIndex() uint64 {
	if x != nil {
		return x.LastLogIndex
	}
	return 0
}

type RequestVoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueueName     string                 `protobuf:"bytes,1,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	Term          uint64                 `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	CandidateId   string                 `protobuf:"bytes,3,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	LastLogIndex  uint64                 `protobuf:"varint,4,opt,name=last_log_index,json=lastLogIndex,proto3" json:"last_log_index,omitempty"`
	LastLogTerm   uint64                 `protobuf:"varint,5,opt,name=last_log_term,json=lastLogTerm,proto3" json:"last_log_term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestVoteRequest) Reset() {
	*x = RequestVoteRequest{}
	mi := &file_cluster_v1_broker_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestVoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestVoteRequest) ProtoMessage() {}

func (x *RequestVoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_broker_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestVoteRequest.ProtoReflect.Descriptor instead.
func (*RequestVoteRequest) Descriptor() ([]byte, []int) {
	return file_cluster_v1_broker_proto_rawDescGZIP(), []int{26}
}

func (x *RequestVoteRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *RequestVoteRequest) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RequestVoteRequest) GetCandidateId() string {
	if x != nil {
		return x.CandidateId
	}
	return ""
}

func (x *RequestVoteRequest) GetLastLogIndex() uint64 {
	if x != nil {
		return x.LastLogIndex
	}
	return 0
}

func (x *RequestVoteRequest) GetLastLogTerm() uint64 {
	if x != nil {
		return x.LastLogTerm
	}
	return 0
}

type RequestVoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          uint64                 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	VoteGranted   bool                   `protobuf:"varint,2,opt,name=vote_granted,json=voteGranted,proto3" json:"vote_granted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestVoteResponse) Reset() {
	*x = RequestVoteResponse{}
	mi := &file_cluster_v1_broker_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestVoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestVoteResponse) ProtoMessage() {}

func (x *RequestVoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_broker_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestVoteResponse.ProtoReflect.Descriptor instead.
func (*RequestVoteResponse) Descriptor() ([]byte, []int) {
	return file_cluster_v1_broker_proto_rawDescGZIP(), []int{27}
}

func (x *RequestVoteResponse) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RequestVoteResponse) GetVoteGranted() bool {
	if x != nil {
		return x.VoteGranted
	}
	return false
}

type InstallSnapshotRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	QueueName         string                 `protobuf:"bytes,1,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	Term              uint64                 `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	LeaderId          string                 `protobuf:"bytes,3,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	LastIncludedIndex uint64                 `protobuf:"varint,4,opt,name=last_included_index,json=lastIncludedIndex,proto3" json:"last_included_index,omitempty"`
	LastIncludedTerm  uint64                 `protobuf:"varint,5,opt,name=last_included_term,json=lastIncludedTerm,proto3" json:"last_included_term,omitempty"`
	Data              []byte                 `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	Done              bool                   `protobuf:"varint,7,opt,name=done,proto3" json:"done,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *InstallSnapshotRequest) Reset() {
	*x = InstallSnapshotRequest{}
	mi := &file_cluster_v1_broker_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallSnapshotRequest) ProtoMessage() {}

func (x *InstallSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_broker_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallSnapshotRequest.ProtoReflect.Descriptor instead.
func (*InstallSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_cluster_v1_broker_proto_rawDescGZIP(), []int{28}
}

func (x *InstallSnapshotRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *InstallSnapshotRequest) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *InstallSnapshotRequest) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

func (x *InstallSnapshotRequest) GetLastIncludedIndex() uint64 {
	if x != nil {
		return x.LastIncludedIndex
	}
	return 0
}

func (x *InstallSnapshotRequest) GetLastIncludedTerm() uint64 {
	if x != nil {
		return x.LastIncludedTerm
	}
	return 0
}

func (x *InstallSnapshotRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *InstallSnapshotRequest) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

type InstallSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          uint64                 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallSnapshotResponse) Reset() {
	*x = InstallSnapshotResponse{}
	mi := &file_cluster_v1_broker_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallSnapshotResponse) ProtoMessage() {}

func (x *InstallSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_broker_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallSnapshotResponse.ProtoReflect.Descriptor instead.
func (*InstallSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_cluster_v1_broker_proto_rawDescGZIP(), []int{29}
}

func (x *InstallSnapshotResponse) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

// ForwardGroupOpRequest carries a consumer group mutation from a follower
// to the Raft leader. op_data is a JSON-encoded raft.Operation struct.
type ForwardGroupOpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueueName     string                 `protobuf:"bytes,1,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	OpData        []byte                 `protobuf:"bytes,2,opt,name=op_data,json=opData,proto3" json:"op_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardGroupOpRequest) Reset() {
	*x = ForwardGroupOpRequest{}
	mi := &file_cluster_v1_broker_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardGroupOpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardGroupOpRequest) ProtoMessage() {}

func (x *ForwardGroupOpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_broker_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardGroupOpRequest.ProtoReflect.Descriptor instead.
func (*ForwardGroupOpRequest) Descriptor() ([]byte, []int) {
	return file_cluster_v1_broker_proto_rawDescGZIP(), []int{30}
}

func (x *ForwardGroupOpRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *ForwardGroupOpRequest) GetOpData() []byte {
	if x != nil {
		return x.OpData
	}
	return nil
}

type ForwardGroupOpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardGroupOpResponse) Reset() {
	*x = ForwardGroupOpResponse{}
	mi := &file_cluster_v1_broker_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardGroupOpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardGroupOpResponse) ProtoMessage() {}

func (x *ForwardGroupOpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_broker_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardGroupOpResponse.ProtoReflect.Descriptor instead.
func (*ForwardGroupOpResponse) Descriptor() ([]byte, []int) {
	return file_cluster_v1_broker_proto_rawDescGZIP(), []int{31}
}

func (x *ForwardGroupOpResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ForwardGroupOpResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ForwardPublishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Qos           uint32                 `protobuf:"varint,3,opt,name=qos,proto3" json:"qos,omitempty"`
	Retain        bool                   `protobuf:"varint,4,opt,name=retain,proto3" json:"retain,omitempty"`
	Properties    map[string]string      `protobuf:"bytes,5,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardPublishRequest) Reset() {
	*x = ForwardPublishRequest{}
	mi := &file_cluster_v1_broker_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardPublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardPublishRequest) ProtoMessage() {}

func (x *ForwardPublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_broker_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardPublishRequest.ProtoReflect.Descriptor instead.
func (*ForwardPublishRequest) Descriptor() ([]byte, []int) {
	return file_cluster_v1_broker_proto_rawDescGZIP(), []int{32}
}

func (x *ForwardPublishRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *ForwardPublishRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ForwardPublishRequest) GetQos() uint32 {
	if x != nil {
		return x.Qos
	}
	return 0
}

func (x *ForwardPublishRequest) GetRetain() bool {
	if x != nil {
		return x.Retain
	}
	return false
}

func (x *ForwardPublishRequest) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

type ForwardPublishBatchRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Messages      []*ForwardPublishRequest `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardPublishBatchRequest) Reset() {
	*x = ForwardPublishBatchRequest{}
	mi := &file_cluster_v1_broker_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardPublishBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardPublishBatchRequest) ProtoMessage() {}

func (x *ForwardPublishBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_broker_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardPublishBatchRequest.ProtoReflect.Descriptor instead.
func (*ForwardPublishBatchRequest) Descriptor() ([]byte, []int) {
	return file_cluster_v1_broker_proto_rawDescGZIP(), []int{33}
}

func (x *ForwardPublishBatchRequest) GetMessages() []*ForwardPublishRequest {
	if x != nil {
		return x.Messages
	}
	return nil
}

type ForwardPublishBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Delivered     uint32                 `protobuf:"varint,3,opt,name=delivered,proto3" json:"delivered,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardPublishBatchResponse) Reset() {
	*x = ForwardPublishBatchResponse{}
	mi := &file_cluster_v1_broker_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardPublishBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardPublishBatchResponse) ProtoMessage() {}

func (x *ForwardPublishBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_broker_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardPublishBatchResponse.ProtoReflect.Descriptor instead.
func (*ForwardPublishBatchResponse) Descriptor() ([]byte, []int) {
	return file_cluster_v1_broker_proto_rawDescGZIP(), []int{34}
}

func (x *ForwardPublishBatchResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ForwardPublishBatchResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ForwardPublishBatchResponse) GetDelivered() uint32 {
	if x != nil {
		return x.Delivered
	}
	return 0
}

var File_cluster_v1_broker_proto protoreflect.FileDescriptor

const file_cluster_v1_broker_proto_rawDesc = "" +
	"\n" +
	"\x17cluster/v1/broker.proto\x12\x11fluxmq.cluster.v1\"\xab\x02\n" +
	"\x0ePublishRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x10\n" +
	"\x03qos\x18\x04 \x01(\rR\x03qos\x12\x16\n" +
	"\x06retain\x18\x05 \x01(\bR\x06retain\x12\x10\n" +
	"\x03dup\x18\x06 \x01(\bR\x03dup\x12Q\n" +
	"\n" +
	"properties\x18\a \x03(\v21.fluxmq.cluster.v1.PublishRequest.PropertiesEntryR\n" +
	"properties\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"A\n" +
	"\x0fPublishResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"T\n" +
	"\x13PublishBatchRequest\x12=\n" +
	"\bmessages\x18\x01 \x03(\v2!.fluxmq.cluster.v1.PublishRequestR\bmessages\"\\\n" +
	"\x11PublishBatchError\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\xa6\x01\n" +
	"\x14PublishBatchResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1c\n" +
	"\tdelivered\x18\x03 \x01(\rR\tdelivered\x12@\n" +
	"\bfailures\x18\x04 \x03(\v2$.fluxmq.cluster.v1.PublishBatchErrorR\bfailures\"d\n" +
	"\x0fTakeoverRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1b\n" +
	"\tfrom_node\x18\x02 \x01(\tR\bfromNode\x12\x17\n" +
	"\ato_node\x18\x03 \x01(\tR\x06toNode\"\x88\x01\n" +
	"\x10TakeoverResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12D\n" +
	"\rsession_state\x18\x03 \x01(\v2\x1f.fluxmq.cluster.v1.SessionStateR\fsessionState\"\xef\x02\n" +
	"\fSessionState\x12'\n" +
	"\x0fexpiry_interval\x18\x01 \x01(\rR\x0eexpiryInterval\x12\x1f\n" +
	"\vclean_start\x18\x02 \x01(\bR\n" +
	"cleanStart\x12O\n" +
	"\x11inflight_messages\x18\x03 \x03(\v2\".fluxmq.cluster.v1.InflightMessageR\x10inflightMessages\x12I\n" +
	"\x0fqueued_messages\x18\x04 \x03(\v2 .fluxmq.cluster.v1.QueuedMessageR\x0equeuedMessages\x12E\n" +
	"\rsubscriptions\x18\x05 \x03(\v2\x1f.fluxmq.cluster.v1.SubscriptionR\rsubscriptions\x122\n" +
	"\x04will\x18\x06 \x01(\v2\x1e.fluxmq.cluster.v1.WillMessageR\x04will\"\xa6\x01\n" +
	"\x0fInflightMessage\x12\x1b\n" +
	"\tpacket_id\x18\x01 \x01(\rR\bpacketId\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x10\n" +
	"\x03qos\x18\x04 \x01(\rR\x03qos\x12\x16\n" +
	"\x06retain\x18\x05 \x01(\bR\x06retain\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\"\x87\x01\n" +
	"\rQueuedMessage\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x10\n" +
	"\x03qos\x18\x03 \x01(\rR\x03qos\x12\x16\n" +
	"\x06retain\x18\x04 \x01(\bR\x06retain\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"8\n" +
	"\fSubscription\x12\x16\n" +
	"\x06filter\x18\x01 \x01(\tR\x06filter\x12\x10\n" +
	"\x03qos\x18\x02 \x01(\rR\x03qos\"\xa6\x01\n" +
	"\vWillMessage\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x10\n" +
	"\x03qos\x18\x03 \x01(\rR\x03qos\x12\x16\n" +
	"\x06retain\x18\x04 \x01(\bR\x06retain\x12\x14\n" +
	"\x05delay\x18\x05 \x01(\rR\x05delay\x12'\n" +
	"\x0fdisconnect_time\x18\x06 \x01(\x03R\x0edisconnectTime\",\n" +
	"\x14FetchRetainedRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\"\x81\x01\n" +
	"\x15FetchRetainedResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12<\n" +
	"\amessage\x18\x02 \x01(\v2\".fluxmq.cluster.v1.RetainedMessageR\amessage\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x9c\x02\n" +
	"\x0fRetainedMessage\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x10\n" +
	"\x03qos\x18\x03 \x01(\rR\x03qos\x12\x16\n" +
	"\x06retain\x18\x04 \x01(\bR\x06retain\x12R\n" +
	"\n" +
	"properties\x18\x05 \x03(\v22.fluxmq.cluster.v1.RetainedMessage.PropertiesEntryR\n" +
	"properties\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"/\n" +
	"\x10FetchWillRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\"y\n" +
	"\x11FetchWillResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x128\n" +
	"\amessage\x18\x02 \x01(\v2\x1e.fluxmq.cluster.v1.WillMessageR\amessage\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\xc0\x02\n" +
	"\x14EnqueueRemoteRequest\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x01 \x01(\tR\tqueueName\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12W\n" +
	"\n" +
	"properties\x18\x03 \x03(\v27.fluxmq.cluster.v1.EnqueueRemoteRequest.PropertiesEntryR\n" +
	"properties\x12+\n" +
	"\x11forwarded_publish\x18\x04 \x01(\bR\x10forwardedPublish\x12*\n" +
	"\x11forward_to_leader\x18\x05 \x01(\bR\x0fforwardToLeader\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"f\n" +
	"\x15EnqueueRemoteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\tR\tmessageId\"\xc7\x02\n" +
	"\x18RouteQueueMessageRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x02 \x01(\tR\tqueueName\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\tR\tmessageId\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12[\n" +
	"\n" +
	"properties\x18\x05 \x03(\v2;.fluxmq.cluster.v1.RouteQueueMessageRequest.PropertiesEntryR\n" +
	"properties\x12\x1a\n" +
	"\bsequence\x18\x06 \x01(\x03R\bsequence\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"K\n" +
	"\x19RouteQueueMessageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"a\n" +
	"\x16RouteQueueBatchRequest\x12G\n" +
	"\bmessages\x18\x01 \x03(\v2+.fluxmq.cluster.v1.RouteQueueMessageRequestR\bmessages\"~\n" +
	"\x14RouteQueueBatchError\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x03 \x01(\tR\tqueueName\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\xac\x01\n" +
	"\x17RouteQueueBatchResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1c\n" +
	"\tdelivered\x18\x03 \x01(\rR\tdelivered\x12C\n" +
	"\bfailures\x18\x04 \x03(\v2'.fluxmq.cluster.v1.RouteQueueBatchErrorR\bfailures\"\xef\x01\n" +
	"\x14AppendEntriesRequest\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x01 \x01(\tR\tqueueName\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x04R\x04term\x12\x1b\n" +
	"\tleader_id\x18\x03 \x01(\tR\bleaderId\x12$\n" +
	"\x0eprev_log_index\x18\x04 \x01(\x04R\fprevLogIndex\x12\"\n" +
	"\rprev_log_term\x18\x05 \x01(\x04R\vprevLogTerm\x12\x18\n" +
	"\aentries\x18\x06 \x03(\fR\aentries\x12#\n" +
	"\rleader_commit\x18\a \x01(\x04R\fleaderCommit\"k\n" +
	"\x15AppendEntriesResponse\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12$\n" +
	"\x0elast_log_index\x18\x03 \x01(\x04R\flastLogIndex\"\xb4\x01\n" +
	"\x12RequestVoteRequest\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x01 \x01(\tR\tqueueName\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x04R\x04term\x12!\n" +
	"\fcandidate_id\x18\x03 \x01(\tR\vcandidateId\x12$\n" +
	"\x0elast_log_index\x18\x04 \x01(\x04R\flastLogIndex\x12\"\n" +
	"\rlast_log_term\x18\x05 \x01(\x04R\vlastLogTerm\"L\n" +
	"\x13RequestVoteResponse\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\x12!\n" +
	"\fvote_granted\x18\x02 \x01(\bR\vvoteGranted\"\xee\x01\n" +
	"\x16InstallSnapshotRequest\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x01 \x01(\tR\tqueueName\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x04R\x04term\x12\x1b\n" +
	"\tleader_id\x18\x03 \x01(\tR\bleaderId\x12.\n" +
	"\x13last_included_index\x18\x04 \x01(\x04R\x11lastIncludedIndex\x12,\n" +
	"\x12last_included_term\x18\x05 \x01(\x04R\x10lastIncludedTerm\x12\x12\n" +
	"\x04data\x18\x06 \x01(\fR\x04data\x12\x12\n" +
	"\x04done\x18\a \x01(\bR\x04done\"-\n" +
	"\x17InstallSnapshotResponse\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\"O\n" +
	"\x15ForwardGroupOpRequest\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x01 \x01(\tR\tqueueName\x12\x17\n" +
	"\aop_data\x18\x02 \x01(\fR\x06opData\"H\n" +
	"\x16ForwardGroupOpResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x8a\x02\n" +
	"\x15ForwardPublishRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x10\n" +
	"\x03qos\x18\x03 \x01(\rR\x03qos\x12\x16\n" +
	"\x06retain\x18\x04 \x01(\bR\x06retain\x12X\n" +
	"\n" +
	"properties\x18\x05 \x03(\v28.fluxmq.cluster.v1.ForwardPublishRequest.PropertiesEntryR\n" +
	"properties\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"b\n" +
	"\x1aForwardPublishBatchRequest\x12D\n" +
	"\bmessages\x18\x01 \x03(\v2(.fluxmq.cluster.v1.ForwardPublishRequestR\bmessages\"k\n" +
	"\x1bForwardPublishBatchResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1c\n" +
	"\tdelivered\x18\x03 \x01(\rR\tdelivered2\xab\n" +
	"\n" +
	"\rBrokerService\x12U\n" +
	"\fRoutePublish\x12!.fluxmq.cluster.v1.PublishRequest\x1a\".fluxmq.cluster.v1.PublishResponse\x12d\n" +
	"\x11RoutePublishBatch\x12&.fluxmq.cluster.v1.PublishBatchRequest\x1a'.fluxmq.cluster.v1.PublishBatchResponse\x12Z\n" +
	"\x0fTakeoverSession\x12\".fluxmq.cluster.v1.TakeoverRequest\x1a#.fluxmq.cluster.v1.TakeoverResponse\x12b\n" +
	"\rFetchRetained\x12'.fluxmq.cluster.v1.FetchRetainedRequest\x1a(.fluxmq.cluster.v1.FetchRetainedResponse\x12V\n" +
	"\tFetchWill\x12#.fluxmq.cluster.v1.FetchWillRequest\x1a$.fluxmq.cluster.v1.FetchWillResponse\x12b\n" +
	"\rEnqueueRemote\x12'.fluxmq.cluster.v1.EnqueueRemoteRequest\x1a(.fluxmq.cluster.v1.EnqueueRemoteResponse\x12n\n" +
	"\x11RouteQueueMessage\x12+.fluxmq.cluster.v1.RouteQueueMessageRequest\x1a,.fluxmq.cluster.v1.RouteQueueMessageResponse\x12h\n" +
	"\x0fRouteQueueBatch\x12).fluxmq.cluster.v1.RouteQueueBatchRequest\x1a*.fluxmq.cluster.v1.RouteQueueBatchResponse\x12b\n" +
	"\rAppendEntries\x12'.fluxmq.cluster.v1.AppendEntriesRequest\x1a(.fluxmq.cluster.v1.AppendEntriesResponse\x12\\\n" +
	"\vRequestVote\x12%.fluxmq.cluster.v1.RequestVoteRequest\x1a&.fluxmq.cluster.v1.RequestVoteResponse\x12h\n" +
	"\x0fInstallSnapshot\x12).fluxmq.cluster.v1.InstallSnapshotRequest\x1a*.fluxmq.cluster.v1.InstallSnapshotResponse\x12e\n" +
	"\x0eForwardGroupOp\x12(.fluxmq.cluster.v1.ForwardGroupOpRequest\x1a).fluxmq.cluster.v1.ForwardGroupOpResponse\x12t\n" +
	"\x13ForwardPublishBatch\x12-.fluxmq.cluster.v1.ForwardPublishBatchRequest\x1a..fluxmq.cluster.v1.ForwardPublishBatchResponseB\xc4\x01\n" +
	"\x15com.fluxmq.cluster.v1B\vBrokerProtoP\x01Z8github.com/absmach/fluxmq/pkg/proto/cluster/v1;clusterv1\xa2\x02\x03FCX\xaa\x02\x11Fluxmq.Cluster.V1\xca\x02\x11Fluxmq\\Cluster\\V1\xe2\x02\x1dFluxmq\\Cluster\\V1\\GPBMetadata\xea\x02\x13Fluxmq::Cluster::V1b\x06proto3"

var (
	file_cluster_v1_broker_proto_rawDescOnce sync.Once
	file_cluster_v1_broker_proto_rawDescData []byte
)

func file_cluster_v1_broker_proto_rawDescGZIP() []byte {
	file_cluster_v1_broker_proto_rawDescOnce.Do(func() {
		file_cluster_v1_broker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cluster_v1_broker_proto_rawDesc), len(file_cluster_v1_broker_proto_rawDesc)))
	})
	return file_cluster_v1_broker_proto_rawDescData
}

var file_cluster_v1_broker_proto_msgTypes = make([]protoimpl.MessageInfo, 40)
var file_cluster_v1_broker_proto_goTypes = []any{
	(*PublishRequest)(nil),              // 0: fluxmq.cluster.v1.PublishRequest
	(*PublishResponse)(nil),             // 1: fluxmq.cluster.v1.PublishResponse
	(*PublishBatchRequest)(nil),         // 2: fluxmq.cluster.v1.PublishBatchRequest
	(*PublishBatchError)(nil),           // 3: fluxmq.cluster.v1.PublishBatchError
	(*PublishBatchResponse)(nil),        // 4: fluxmq.cluster.v1.PublishBatchResponse
	(*TakeoverRequest)(nil),             // 5: fluxmq.cluster.v1.TakeoverRequest
	(*TakeoverResponse)(nil),            // 6: fluxmq.cluster.v1.TakeoverResponse
	(*SessionState)(nil),                // 7: fluxmq.cluster.v1.SessionState
	(*InflightMessage)(nil),             // 8: fluxmq.cluster.v1.InflightMessage
	(*QueuedMessage)(nil),               // 9: fluxmq.cluster.v1.QueuedMessage
	(*Subscription)(nil),                // 10: fluxmq.cluster.v1.Subscription
	(*WillMessage)(nil),                 // 11: fluxmq.cluster.v1.WillMessage
	(*FetchRetainedRequest)(nil),        // 12: fluxmq.cluster.v1.FetchRetainedRequest
	(*FetchRetainedResponse)(nil),       // 13: fluxmq.cluster.v1.FetchRetainedResponse
	(*RetainedMessage)(nil),             // 14: fluxmq.cluster.v1.RetainedMessage
	(*FetchWillRequest)(nil),            // 15: fluxmq.cluster.v1.FetchWillRequest
	(*FetchWillResponse)(nil),           // 16: fluxmq.cluster.v1.FetchWillResponse
	(*EnqueueRemoteRequest)(nil),        // 17: fluxmq.cluster.v1.EnqueueRemoteRequest
	(*EnqueueRemoteResponse)(nil),       // 18: fluxmq.cluster.v1.EnqueueRemoteResponse
	(*RouteQueueMessageRequest)(nil),    // 19: fluxmq.cluster.v1.RouteQueueMessageRequest
	(*RouteQueueMessageResponse)(nil),   // 20: fluxmq.cluster.v1.RouteQueueMessageResponse
	(*RouteQueueBatchRequest)(nil),      // 21: fluxmq.cluster.v1.RouteQueueBatchRequest
	(*RouteQueueBatchError)(nil),        // 22: fluxmq.cluster.v1.RouteQueueBatchError
	(*RouteQueueBatchResponse)(nil),     // 23: fluxmq.cluster.v1.RouteQueueBatchResponse
	(*AppendEntriesRequest)(nil),        // 24: fluxmq.cluster.v1.AppendEntriesRequest
	(*AppendEntriesResponse)(nil),       // 25: fluxmq.cluster.v1.AppendEntriesResponse
	(*RequestVoteRequest)(nil),          // 26: fluxmq.cluster.v1.RequestVoteRequest
	(*RequestVoteResponse)(nil),         // 27: fluxmq.cluster.v1.RequestVoteResponse
	(*InstallSnapshotRequest)(nil),      // 28: fluxmq.cluster.v1.InstallSnapshotRequest
	(*InstallSnapshotResponse)(nil),     // 29: fluxmq.cluster.v1.InstallSnapshotResponse
	(*ForwardGroupOpRequest)(nil),       // 30: fluxmq.cluster.v1.ForwardGroupOpRequest
	(*ForwardGroupOpResponse)(nil),      // 31: fluxmq.cluster.v1.ForwardGroupOpResponse
	(*ForwardPublishRequest)(nil),       // 32: fluxmq.cluster.v1.ForwardPublishRequest
	(*ForwardPublishBatchRequest)(nil),  // 33: fluxmq.cluster.v1.ForwardPublishBatchRequest
	(*ForwardPublishBatchResponse)(nil), // 34: fluxmq.cluster.v1.ForwardPublishBatchResponse
	nil,                                 // 35: fluxmq.cluster.v1.PublishRequest.PropertiesEntry
	nil,                                 // 36: fluxmq.cluster.v1.RetainedMessage.PropertiesEntry
	nil,                                 // 37: fluxmq.cluster.v1.EnqueueRemoteRequest.PropertiesEntry
	nil,                                 // 38: fluxmq.cluster.v1.RouteQueueMessageRequest.PropertiesEntry
	nil,                                 // 39: fluxmq.cluster.v1.ForwardPublishRequest.PropertiesEntry
}
var file_cluster_v1_broker_proto_depIdxs = []int32{
	35, // 0: fluxmq.cluster.v1.PublishRequest.properties:type_name -> fluxmq.cluster.v1.PublishRequest.PropertiesEntry
	0,  // 1: fluxmq.cluster.v1.PublishBatchRequest.messages:type_name -> fluxmq.cluster.v1.PublishRequest
	3,  // 2: fluxmq.cluster.v1.PublishBatchResponse.failures:type_name -> fluxmq.cluster.v1.PublishBatchError
	7,  // 3: fluxmq.cluster.v1.TakeoverResponse.session_state:type_name -> fluxmq.cluster.v1.SessionState
	8,  // 4: fluxmq.cluster.v1.SessionState.inflight_messages:type_name -> fluxmq.cluster.v1.InflightMessage
	9,  // 5: fluxmq.cluster.v1.SessionState.queued_messages:type_name -> fluxmq.cluster.v1.QueuedMessage
	10, // 6: fluxmq.cluster.v1.SessionState.subscriptions:type_name -> fluxmq.cluster.v1.Subscription
	11, // 7: fluxmq.cluster.v1.SessionState.will:type_name -> fluxmq.cluster.v1.WillMessage
	14, // 8: fluxmq.cluster.v1.FetchRetainedResponse.message:type_name -> fluxmq.cluster.v1.RetainedMessage
	36, // 9: fluxmq.cluster.v1.RetainedMessage.properties:type_name -> fluxmq.cluster.v1.RetainedMessage.PropertiesEntry
	11, // 10: fluxmq.cluster.v1.FetchWillResponse.message:type_name -> fluxmq.cluster.v1.WillMessage
	37, // 11: fluxmq.cluster.v1.EnqueueRemoteRequest.properties:type_name -> fluxmq.cluster.v1.EnqueueRemoteRequest.PropertiesEntry
	38, // 12: fluxmq.cluster.v1.RouteQueueMessageRequest.properties:type_name -> fluxmq.cluster.v1.RouteQueueMessageRequest.PropertiesEntry
	19, // 13: fluxmq.cluster.v1.RouteQueueBatchRequest.messages:type_name -> fluxmq.cluster.v1.RouteQueueMessageRequest
	22, // 14: fluxmq.cluster.v1.RouteQueueBatchResponse.failures:type_name -> fluxmq.cluster.v1.RouteQueueBatchError
	39, // 15: fluxmq.cluster.v1.ForwardPublishRequest.properties:type_name -> fluxmq.cluster.v1.ForwardPublishRequest.PropertiesEntry
	32, // 16: fluxmq.cluster.v1.ForwardPublishBatchRequest.messages:type_name -> fluxmq.cluster.v1.ForwardPublishRequest
	0,  // 17: fluxmq.cluster.v1.BrokerService.RoutePublish:input_type -> fluxmq.cluster.v1.PublishRequest
	2,  // 18: fluxmq.cluster.v1.BrokerService.RoutePublishBatch:input_type -> fluxmq.cluster.v1.PublishBatchRequest
	5,  // 19: fluxmq.cluster.v1.BrokerService.TakeoverSession:input_type -> fluxmq.cluster.v1.TakeoverRequest
	12, // 20: fluxmq.cluster.v1.BrokerService.FetchRetained:input_type -> fluxmq.cluster.v1.FetchRetainedRequest
	15, // 21: fluxmq.cluster.v1.BrokerService.FetchWill:input_type -> fluxmq.cluster.v1.FetchWillRequest
	17, // 22: fluxmq.cluster.v1.BrokerService.EnqueueRemote:input_type -> fluxmq.cluster.v1.EnqueueRemoteRequest
	19, // 23: fluxmq.cluster.v1.BrokerService.RouteQueueMessage:input_type -> fluxmq.cluster.v1.RouteQueueMessageRequest
	21, // 24: fluxmq.cluster.v1.BrokerService.RouteQueueBatch:input_type -> fluxmq.cluster.v1.RouteQueueBatchRequest
	24, // 25: fluxmq.cluster.v1.BrokerService.AppendEntries:input_type -> fluxmq.cluster.v1.AppendEntriesRequest
	26, // 26: fluxmq.cluster.v1.BrokerService.RequestVote:input_type -> fluxmq.cluster.v1.RequestVoteRequest
	28, // 27: fluxmq.cluster.v1.BrokerService.InstallSnapshot:input_type -> fluxmq.cluster.v1.InstallSnapshotRequest
	30, // 28: fluxmq.cluster.v1.BrokerService.ForwardGroupOp:input_type -> fluxmq.cluster.v1.ForwardGroupOpRequest
	33, // 29: fluxmq.cluster.v1.BrokerService.ForwardPublishBatch:input_type -> fluxmq.cluster.v1.ForwardPublishBatchRequest
	1,  // 30: fluxmq.cluster.v1.BrokerService.RoutePublish:output_type -> fluxmq.cluster.v1.PublishResponse
	4,  // 31: fluxmq.cluster.v1.BrokerService.RoutePublishBatch:output_type -> fluxmq.cluster.v1.PublishBatchResponse
	6,  // 32: fluxmq.cluster.v1.BrokerService.TakeoverSession:output_type -> fluxmq.cluster.v1.TakeoverResponse
	13, // 33: fluxmq.cluster.v1.BrokerService.FetchRetained:output_type -> fluxmq.cluster.v1.FetchRetainedResponse
	16, // 34: fluxmq.cluster.v1.BrokerService.FetchWill:output_type -> fluxmq.cluster.v1.FetchWillResponse
	18, // 35: fluxmq.cluster.v1.BrokerService.EnqueueRemote:output_type -> fluxmq.cluster.v1.EnqueueRemoteResponse
	20, // 36: fluxmq.cluster.v1.BrokerService.RouteQueueMessage:output_type -> fluxmq.cluster.v1.RouteQueueMessageResponse
	23, // 37: fluxmq.cluster.v1.BrokerService.RouteQueueBatch:output_type -> fluxmq.cluster.v1.RouteQueueBatchResponse
	25, // 38: fluxmq.cluster.v1.BrokerService.AppendEntries:output_type -> fluxmq.cluster.v1.AppendEntriesResponse
	27, // 39: fluxmq.cluster.v1.BrokerService.RequestVote:output_type -> fluxmq.cluster.v1.RequestVoteResponse
	29, // 40: fluxmq.cluster.v1.BrokerService.InstallSnapshot:output_type -> fluxmq.cluster.v1.InstallSnapshotResponse
	31, // 41: fluxmq.cluster.v1.BrokerService.ForwardGroupOp:output_type -> fluxmq.cluster.v1.ForwardGroupOpResponse
	34, // 42: fluxmq.cluster.v1.BrokerService.ForwardPublishBatch:output_type -> fluxmq.cluster.v1.ForwardPublishBatchResponse
	30, // [30:43] is the sub-list for method output_type
	17, // [17:30] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_cluster_v1_broker_proto_init() }
func file_cluster_v1_broker_proto_init() {
	if File_cluster_v1_broker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cluster_v1_broker_proto_rawDesc), len(file_cluster_v1_broker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   40,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cluster_v1_broker_proto_goTypes,
		DependencyIndexes: file_cluster_v1_broker_proto_depIdxs,
		MessageInfos:      file_cluster_v1_broker_proto_msgTypes,
	}.Build()
	File_cluster_v1_broker_proto = out.File
	file_cluster_v1_broker_proto_goTypes = nil
	file_cluster_v1_broker_proto_depIdxs = nil
}
