// Copyright (c) Abstract Machines
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: atom/v1/atom.proto

package atomv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/absmach/fluxmq/pkg/proto/atom/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AuthzServiceName is the fully-qualified name of the AuthzService service.
	AuthzServiceName = "atom.v1.AuthzService"
	// AuthServiceName is the fully-qualified name of the AuthService service.
	AuthServiceName = "atom.v1.AuthService"
	// CertificateServiceName is the fully-qualified name of the CertificateService service.
	CertificateServiceName = "atom.v1.CertificateService"
	// AliasServiceName is the fully-qualified name of the AliasService service.
	AliasServiceName = "atom.v1.AliasService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AuthzServiceCheckProcedure is the fully-qualified name of the AuthzService's Check RPC.
	AuthzServiceCheckProcedure = "/atom.v1.AuthzService/Check"
	// AuthServiceAuthenticateProcedure is the fully-qualified name of the AuthService's Authenticate
	// RPC.
	AuthServiceAuthenticateProcedure = "/atom.v1.AuthService/Authenticate"
	// AuthServiceAuthenticateCredentialProcedure is the fully-qualified name of the AuthService's
	// AuthenticateCredential RPC.
	AuthServiceAuthenticateCredentialProcedure = "/atom.v1.AuthService/AuthenticateCredential"
	// CertificateServiceResolveCertificateProcedure is the fully-qualified name of the
	// CertificateService's ResolveCertificate RPC.
	CertificateServiceResolveCertificateProcedure = "/atom.v1.CertificateService/ResolveCertificate"
	// CertificateServiceRevokeEntityCertificatesProcedure is the fully-qualified name of the
	// CertificateService's RevokeEntityCertificates RPC.
	CertificateServiceRevokeEntityCertificatesProcedure = "/atom.v1.CertificateService/RevokeEntityCertificates"
	// AliasServiceResolveAliasProcedure is the fully-qualified name of the AliasService's ResolveAlias
	// RPC.
	AliasServiceResolveAliasProcedure = "/atom.v1.AliasService/ResolveAlias"
)

// AuthzServiceClient is a client for the atom.v1.AuthzService service.
type AuthzServiceClient interface {
	Check(context.Context, *connect.Request[v1.CheckRequest]) (*connect.Response[v1.CheckResponse], error)
}

// NewAuthzServiceClient constructs a client for the atom.v1.AuthzService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAuthzServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AuthzServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	authzServiceMethods := v1.File_atom_v1_atom_proto.Services().ByName("AuthzService").Methods()
	return &authzServiceClient{
		check: connect.NewClient[v1.CheckRequest, v1.CheckResponse](
			httpClient,
			baseURL+AuthzServiceCheckProcedure,
			connect.WithSchema(authzServiceMethods.ByName("Check")),
			connect.WithClientOptions(opts...),
		),
	}
}

// authzServiceClient implements AuthzServiceClient.
type authzServiceClient struct {
	check *connect.Client[v1.CheckRequest, v1.CheckResponse]
}

// Check calls atom.v1.AuthzService.Check.
func (c *authzServiceClient) Check(ctx context.Context, req *connect.Request[v1.CheckRequest]) (*connect.Response[v1.CheckResponse], error) {
	return c.check.CallUnary(ctx, req)
}

// AuthzServiceHandler is an implementation of the atom.v1.AuthzService service.
type AuthzServiceHandler interface {
	Check(context.Context, *connect.Request[v1.CheckRequest]) (*connect.Response[v1.CheckResponse], error)
}

// NewAuthzServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAuthzServiceHandler(svc AuthzServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	authzServiceMethods := v1.File_atom_v1_atom_proto.Services().ByName("AuthzService").Methods()
	authzServiceCheckHandler := connect.NewUnaryHandler(
		AuthzServiceCheckProcedure,
		svc.Check,
		connect.WithSchema(authzServiceMethods.ByName("Check")),
		connect.WithHandlerOptions(opts...),
	)
	return "/atom.v1.AuthzService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AuthzServiceCheckProcedure:
			authzServiceCheckHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAuthzServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAuthzServiceHandler struct{}

func (UnimplementedAuthzServiceHandler) Check(context.Context, *connect.Request[v1.CheckRequest]) (*connect.Response[v1.CheckResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("atom.v1.AuthzService.Check is not implemented"))
}

// AuthServiceClient is a client for the atom.v1.AuthService service.
type AuthServiceClient interface {
	Authenticate(context.Context, *connect.Request[v1.AuthenticateRequest]) (*connect.Response[v1.AuthenticateResponse], error)
	AuthenticateCredential(context.Context, *connect.Request[v1.AuthenticateCredentialRequest]) (*connect.Response[v1.AuthenticateCredentialResponse], error)
}

// NewAuthServiceClient constructs a client for the atom.v1.AuthService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAuthServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AuthServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	authServiceMethods := v1.File_atom_v1_atom_proto.Services().ByName("AuthService").Methods()
	return &authServiceClient{
		authenticate: connect.NewClient[v1.AuthenticateRequest, v1.AuthenticateResponse](
			httpClient,
			baseURL+AuthServiceAuthenticateProcedure,
			connect.WithSchema(authServiceMethods.ByName("Authenticate")),
			connect.WithClientOptions(opts...),
		),
		authenticateCredential: connect.NewClient[v1.AuthenticateCredentialRequest, v1.AuthenticateCredentialResponse](
			httpClient,
			baseURL+AuthServiceAuthenticateCredentialProcedure,
			connect.WithSchema(authServiceMethods.ByName("AuthenticateCredential")),
			connect.WithClientOptions(opts...),
		),
	}
}

// authServiceClient implements AuthServiceClient.
type authServiceClient struct {
	authenticate           *connect.Client[v1.AuthenticateRequest, v1.AuthenticateResponse]
	authenticateCredential *connect.Client[v1.AuthenticateCredentialRequest, v1.AuthenticateCredentialResponse]
}

// Authenticate calls atom.v1.AuthService.Authenticate.
func (c *authServiceClient) Authenticate(ctx context.Context, req *connect.Request[v1.AuthenticateRequest]) (*connect.Response[v1.AuthenticateResponse], error) {
	return c.authenticate.CallUnary(ctx, req)
}

// AuthenticateCredential calls atom.v1.AuthService.AuthenticateCredential.
func (c *authServiceClient) AuthenticateCredential(ctx context.Context, req *connect.Request[v1.AuthenticateCredentialRequest]) (*connect.Response[v1.AuthenticateCredentialResponse], error) {
	return c.authenticateCredential.CallUnary(ctx, req)
}

// AuthServiceHandler is an implementation of the atom.v1.AuthService service.
type AuthServiceHandler interface {
	Authenticate(context.Context, *connect.Request[v1.AuthenticateRequest]) (*connect.Response[v1.AuthenticateResponse], error)
	AuthenticateCredential(context.Context, *connect.Request[v1.AuthenticateCredentialRequest]) (*connect.Response[v1.AuthenticateCredentialResponse], error)
}

// NewAuthServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAuthServiceHandler(svc AuthServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	authServiceMethods := v1.File_atom_v1_atom_proto.Services().ByName("AuthService").Methods()
	authServiceAuthenticateHandler := connect.NewUnaryHandler(
		AuthServiceAuthenticateProcedure,
		svc.Authenticate,
		connect.WithSchema(authServiceMethods.ByName("Authenticate")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceAuthenticateCredentialHandler := connect.NewUnaryHandler(
		AuthServiceAuthenticateCredentialProcedure,
		svc.AuthenticateCredential,
		connect.WithSchema(authServiceMethods.ByName("AuthenticateCredential")),
		connect.WithHandlerOptions(opts...),
	)
	return "/atom.v1.AuthService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AuthServiceAuthenticateProcedure:
			authServiceAuthenticateHandler.ServeHTTP(w, r)
		case AuthServiceAuthenticateCredentialProcedure:
			authServiceAuthenticateCredentialHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAuthServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAuthServiceHandler struct{}

func (UnimplementedAuthServiceHandler) Authenticate(context.Context, *connect.Request[v1.AuthenticateRequest]) (*connect.Response[v1.AuthenticateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("atom.v1.AuthService.Authenticate is not implemented"))
}

func (UnimplementedAuthServiceHandler) AuthenticateCredential(context.Context, *connect.Request[v1.AuthenticateCredentialRequest]) (*connect.Response[v1.AuthenticateCredentialResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("atom.v1.AuthService.AuthenticateCredential is not implemented"))
}

// CertificateServiceClient is a client for the atom.v1.CertificateService service.
type CertificateServiceClient interface {
	ResolveCertificate(context.Context, *connect.Request[v1.ResolveCertificateRequest]) (*connect.Response[v1.ResolveCertificateResponse], error)
	RevokeEntityCertificates(context.Context, *connect.Request[v1.RevokeEntityCertificatesRequest]) (*connect.Response[v1.RevokeEntityCertificatesResponse], error)
}

// NewCertificateServiceClient constructs a client for the atom.v1.CertificateService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewCertificateServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) CertificateServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	certificateServiceMethods := v1.File_atom_v1_atom_proto.Services().ByName("CertificateService").Methods()
	return &certificateServiceClient{
		resolveCertificate: connect.NewClient[v1.ResolveCertificateRequest, v1.ResolveCertificateResponse](
			httpClient,
			baseURL+CertificateServiceResolveCertificateProcedure,
			connect.WithSchema(certificateServiceMethods.ByName("ResolveCertificate")),
			connect.WithClientOptions(opts...),
		),
		revokeEntityCertificates: connect.NewClient[v1.RevokeEntityCertificatesRequest, v1.RevokeEntityCertificatesResponse](
			httpClient,
			baseURL+CertificateServiceRevokeEntityCertificatesProcedure,
			connect.WithSchema(certificateServiceMethods.ByName("RevokeEntityCertificates")),
			connect.WithClientOptions(opts...),
		),
	}
}

// certificateServiceClient implements CertificateServiceClient.
type certificateServiceClient struct {
	resolveCertificate       *connect.Client[v1.ResolveCertificateRequest, v1.ResolveCertificateResponse]
	revokeEntityCertificates *connect.Client[v1.RevokeEntityCertificatesRequest, v1.RevokeEntityCertificatesResponse]
}

// ResolveCertificate calls atom.v1.CertificateService.ResolveCertificate.
func (c *certificateServiceClient) ResolveCertificate(ctx context.Context, req *connect.Request[v1.ResolveCertificateRequest]) (*connect.Response[v1.ResolveCertificateResponse], error) {
	return c.resolveCertificate.CallUnary(ctx, req)
}

// RevokeEntityCertificates calls atom.v1.CertificateService.RevokeEntityCertificates.
func (c *certificateServiceClient) RevokeEntityCertificates(ctx context.Context, req *connect.Request[v1.RevokeEntityCertificatesRequest]) (*connect.Response[v1.RevokeEntityCertificatesResponse], error) {
	return c.revokeEntityCertificates.CallUnary(ctx, req)
}

// CertificateServiceHandler is an implementation of the atom.v1.CertificateService service.
type CertificateServiceHandler interface {
	ResolveCertificate(context.Context, *connect.Request[v1.ResolveCertificateRequest]) (*connect.Response[v1.ResolveCertificateResponse], error)
	RevokeEntityCertificates(context.Context, *connect.Request[v1.RevokeEntityCertificatesRequest]) (*connect.Response[v1.RevokeEntityCertificatesResponse], error)
}

// NewCertificateServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewCertificateServiceHandler(svc CertificateServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	certificateServiceMethods := v1.File_atom_v1_atom_proto.Services().ByName("CertificateService").Methods()
	certificateServiceResolveCertificateHandler := connect.NewUnaryHandler(
		CertificateServiceResolveCertificateProcedure,
		svc.ResolveCertificate,
		connect.WithSchema(certificateServiceMethods.ByName("ResolveCertificate")),
		connect.WithHandlerOptions(opts...),
	)
	certificateServiceRevokeEntityCertificatesHandler := connect.NewUnaryHandler(
		CertificateServiceRevokeEntityCertificatesProcedure,
		svc.RevokeEntityCertificates,
		connect.WithSchema(certificateServiceMethods.ByName("RevokeEntityCertificates")),
		connect.WithHandlerOptions(opts...),
	)
	return "/atom.v1.CertificateService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case CertificateServiceResolveCertificateProcedure:
			certificateServiceResolveCertificateHandler.ServeHTTP(w, r)
		case CertificateServiceRevokeEntityCertificatesProcedure:
			certificateServiceRevokeEntityCertificatesHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedCertificateServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedCertificateServiceHandler struct{}

func (UnimplementedCertificateServiceHandler) ResolveCertificate(context.Context, *connect.Request[v1.ResolveCertificateRequest]) (*connect.Response[v1.ResolveCertificateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("atom.v1.CertificateService.ResolveCertificate is not implemented"))
}

func (UnimplementedCertificateServiceHandler) RevokeEntityCertificates(context.Context, *connect.Request[v1.RevokeEntityCertificatesRequest]) (*connect.Response[v1.RevokeEntityCertificatesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("atom.v1.CertificateService.RevokeEntityCertificates is not implemented"))
}

// AliasServiceClient is a client for the atom.v1.AliasService service.
type AliasServiceClient interface {
	ResolveAlias(context.Context, *connect.Request[v1.ResolveAliasRequest]) (*connect.Response[v1.ResolveAliasResponse], error)
}

// NewAliasServiceClient constructs a client for the atom.v1.AliasService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAliasServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AliasServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	aliasServiceMethods := v1.File_atom_v1_atom_proto.Services().ByName("AliasService").Methods()
	return &aliasServiceClient{
		resolveAlias: connect.NewClient[v1.ResolveAliasRequest, v1.ResolveAliasResponse](
			httpClient,
			baseURL+AliasServiceResolveAliasProcedure,
			connect.WithSchema(aliasServiceMethods.ByName("ResolveAlias")),
			connect.WithClientOptions(opts...),
		),
	}
}

// aliasServiceClient implements AliasServiceClient.
type aliasServiceClient struct {
	resolveAlias *connect.Client[v1.ResolveAliasRequest, v1.ResolveAliasResponse]
}

// ResolveAlias calls atom.v1.AliasService.ResolveAlias.
func (c *aliasServiceClient) ResolveAlias(ctx context.Context, req *connect.Request[v1.ResolveAliasRequest]) (*connect.Response[v1.ResolveAliasResponse], error) {
	return c.resolveAlias.CallUnary(ctx, req)
}

// AliasServiceHandler is an implementation of the atom.v1.AliasService service.
type AliasServiceHandler interface {
	ResolveAlias(context.Context, *connect.Request[v1.ResolveAliasRequest]) (*connect.Response[v1.ResolveAliasResponse], error)
}

// NewAliasServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAliasServiceHandler(svc AliasServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	aliasServiceMethods := v1.File_atom_v1_atom_proto.Services().ByName("AliasService").Methods()
	aliasServiceResolveAliasHandler := connect.NewUnaryHandler(
		AliasServiceResolveAliasProcedure,
		svc.ResolveAlias,
		connect.WithSchema(aliasServiceMethods.ByName("ResolveAlias")),
		connect.WithHandlerOptions(opts...),
	)
	return "/atom.v1.AliasService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AliasServiceResolveAliasProcedure:
			aliasServiceResolveAliasHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAliasServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAliasServiceHandler struct{}

func (UnimplementedAliasServiceHandler) ResolveAlias(context.Context, *connect.Request[v1.ResolveAliasRequest]) (*connect.Response[v1.ResolveAliasResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("atom.v1.AliasService.ResolveAlias is not implemented"))
}
