// Copyright (c) Abstract Machines
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: message/v1/envelope.proto

package messagev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Envelope is the format every stored broker message is written in.
//
// This file is the schema of record. The implementation is the hand-written
// codec in message/codec.go, and message/conformance_test.go holds the two
// against each other: the hand codec's bytes must parse into these messages
// field for field, and a golden encoding is pinned in
// message/testdata/envelope-v1.bin. A change to one that is not made in the
// other fails that test.
//
// It exists because the persisted format was previously defined only by two Go
// switch statements kept aligned by hand, so a reviewer of a change to it had
// no artefact to review. Every stored message depends on this format; the
// client-facing RPC schemas, whose worst failure is a broken call, already had
// one.
type Envelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// version is mandatory and is always written, so a valid encoding is never
	// empty. Decoders reject any value other than 1.
	Version uint32 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Topic   string `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	// payload and publisher.key are omitted in metadata-only encodings, where the
	// log record holds the value and key beside the metadata rather than inside
	// it. A metadata blob that carries either of them is rejected rather than
	// silently preferred over the record's own.
	Payload       []byte             `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Publisher     *PublisherMetadata `protobuf:"bytes,4,opt,name=publisher,proto3" json:"publisher,omitempty"`
	Broker        *BrokerMetadata    `protobuf:"bytes,5,opt,name=broker,proto3" json:"broker,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_message_v1_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_message_v1_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_message_v1_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Envelope) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Envelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetPublisher() *PublisherMetadata {
	if x != nil {
		return x.Publisher
	}
	return nil
}

func (x *Envelope) GetBroker() *BrokerMetadata {
	if x != nil {
		return x.Broker
	}
	return nil
}

// PublisherMetadata is what the publisher owns. The broker never interprets it
// beyond filtering reserved property names at ingress.
type PublisherMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// See Envelope.payload: omitted in metadata-only encodings.
	Key             []byte            `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Headers         map[string][]byte `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Properties      map[string]string `protobuf:"bytes,3,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ContentType     string            `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	ContentEncoding string            `protobuf:"bytes,5,opt,name=content_encoding,json=contentEncoding,proto3" json:"content_encoding,omitempty"`
	ResponseTopic   string            `protobuf:"bytes,6,opt,name=response_topic,json=responseTopic,proto3" json:"response_topic,omitempty"`
	CorrelationData []byte            `protobuf:"bytes,7,opt,name=correlation_data,json=correlationData,proto3" json:"correlation_data,omitempty"`
	// payload_format and message_expiry are optional so that "absent" stays
	// distinguishable from an explicit zero, which is what they are in the Go
	// representation.
	PayloadFormat *uint32 `protobuf:"varint,8,opt,name=payload_format,json=payloadFormat,proto3,oneof" json:"payload_format,omitempty"`
	MessageExpiry *uint32 `protobuf:"varint,9,opt,name=message_expiry,json=messageExpiry,proto3,oneof" json:"message_expiry,omitempty"`
	// message_id is the publisher's own identifier, as carried by AMQP. The
	// broker's handle for a durable delivery is derived from the queue and
	// offset instead, and is never stored.
	MessageId     string `protobuf:"bytes,10,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublisherMetadata) Reset() {
	*x = PublisherMetadata{}
	mi := &file_message_v1_envelope_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublisherMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublisherMetadata) ProtoMessage() {}

func (x *PublisherMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_message_v1_envelope_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublisherMetadata.ProtoReflect.Descriptor instead.
func (*PublisherMetadata) Descriptor() ([]byte, []int) {
	return file_message_v1_envelope_proto_rawDescGZIP(), []int{1}
}

func (x *PublisherMetadata) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *PublisherMetadata) GetHeaders() map[string][]byte {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *PublisherMetadata) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *PublisherMetadata) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *PublisherMetadata) GetContentEncoding() string {
	if x != nil {
		return x.ContentEncoding
	}
	return ""
}

func (x *PublisherMetadata) GetResponseTopic() string {
	if x != nil {
		return x.ResponseTopic
	}
	return ""
}

func (x *PublisherMetadata) GetCorrelationData() []byte {
	if x != nil {
		return x.CorrelationData
	}
	return nil
}

func (x *PublisherMetadata) GetPayloadFormat() uint32 {
	if x != nil && x.PayloadFormat != nil {
		return *x.PayloadFormat
	}
	return 0
}

func (x *PublisherMetadata) GetMessageExpiry() uint32 {
	if x != nil && x.MessageExpiry != nil {
		return *x.MessageExpiry
	}
	return 0
}

func (x *PublisherMetadata) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

// BrokerMetadata is what the broker owns. It is never accepted from an
// untrusted peer.
type BrokerMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        *SourceMetadata        `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Delivery      *DeliveryMetadata      `protobuf:"bytes,2,opt,name=delivery,proto3" json:"delivery,omitempty"`
	Queue         *QueueMetadata         `protobuf:"bytes,3,opt,name=queue,proto3" json:"queue,omitempty"`
	Transfer      *TransferMetadata      `protobuf:"bytes,4,opt,name=transfer,proto3" json:"transfer,omitempty"`
	Trace         *TraceMetadata         `protobuf:"bytes,5,opt,name=trace,proto3" json:"trace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrokerMetadata) Reset() {
	*x = BrokerMetadata{}
	mi := &file_message_v1_envelope_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrokerMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrokerMetadata) ProtoMessage() {}

func (x *BrokerMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_message_v1_envelope_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrokerMetadata.ProtoReflect.Descriptor instead.
func (*BrokerMetadata) Descriptor() ([]byte, []int) {
	return file_message_v1_envelope_proto_rawDescGZIP(), []int{2}
}

func (x *BrokerMetadata) GetSource() *SourceMetadata {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *BrokerMetadata) GetDelivery() *DeliveryMetadata {
	if x != nil {
		return x.Delivery
	}
	return nil
}

func (x *BrokerMetadata) GetQueue() *QueueMetadata {
	if x != nil {
		return x.Queue
	}
	return nil
}

func (x *BrokerMetadata) GetTransfer() *TransferMetadata {
	if x != nil {
		return x.Transfer
	}
	return nil
}

func (x *BrokerMetadata) GetTrace() *TraceMetadata {
	if x != nil {
		return x.Trace
	}
	return nil
}

// SourceMetadata identifies the authenticated origin of a message.
type SourceMetadata struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	ClientId   string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ExternalId string                 `protobuf:"bytes,2,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	// protocol is a string rather than an enum because that is what the codec
	// writes today. An enum would cost less per record and reject an unknown
	// value at the boundary.
	Protocol string `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	// topic is the topic the message was published to, before any queue
	// delivery address was derived from it.
	Topic         string `protobuf:"bytes,4,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceMetadata) Reset() {
	*x = SourceMetadata{}
	mi := &file_message_v1_envelope_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceMetadata) ProtoMessage() {}

func (x *SourceMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_message_v1_envelope_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceMetadata.ProtoReflect.Descriptor instead.
func (*SourceMetadata) Descriptor() ([]byte, []int) {
	return file_message_v1_envelope_proto_rawDescGZIP(), []int{3}
}

func (x *SourceMetadata) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *SourceMetadata) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *SourceMetadata) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *SourceMetadata) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

// DeliveryMetadata carries the protocol transaction state of one delivery.
type DeliveryMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Timestamps are zigzag-encoded Unix nanoseconds, and a zero time is omitted
	// rather than written as the epoch.
	PublishedAt int64 `protobuf:"zigzag64,1,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	ExpiresAt   int64 `protobuf:"zigzag64,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// subscription_ids is deliberately unpacked, which is what the hand codec
	// writes. Packing it would be smaller and is what a generated encoder emits
	// by default, so changing it is a change to the stored format.
	SubscriptionIds []uint32 `protobuf:"varint,3,rep,name=subscription_ids,json=subscriptionIds,proto3" json:"subscription_ids,omitempty"`
	PacketId        uint32   `protobuf:"varint,4,opt,name=packet_id,json=packetId,proto3" json:"packet_id,omitempty"`
	Qos             uint32   `protobuf:"varint,5,opt,name=qos,proto3" json:"qos,omitempty"`
	// direction: 0 = outbound (server->client), 1 = inbound (client->server).
	InflightDirection uint32 `protobuf:"varint,6,opt,name=inflight_direction,json=inflightDirection,proto3" json:"inflight_direction,omitempty"`
	// state: 0 = publish sent, 1 = pubrec received.
	InflightState uint32 `protobuf:"varint,7,opt,name=inflight_state,json=inflightState,proto3" json:"inflight_state,omitempty"`
	Retain        bool   `protobuf:"varint,8,opt,name=retain,proto3" json:"retain,omitempty"`
	Duplicate     bool   `protobuf:"varint,9,opt,name=duplicate,proto3" json:"duplicate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveryMetadata) Reset() {
	*x = DeliveryMetadata{}
	mi := &file_message_v1_envelope_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryMetadata) ProtoMessage() {}

func (x *DeliveryMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_message_v1_envelope_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryMetadata.ProtoReflect.Descriptor instead.
func (*DeliveryMetadata) Descriptor() ([]byte, []int) {
	return file_message_v1_envelope_proto_rawDescGZIP(), []int{4}
}

func (x *DeliveryMetadata) GetPublishedAt() int64 {
	if x != nil {
		return x.PublishedAt
	}
	return 0
}

func (x *DeliveryMetadata) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *DeliveryMetadata) GetSubscriptionIds() []uint32 {
	if x != nil {
		return x.SubscriptionIds
	}
	return nil
}

func (x *DeliveryMetadata) GetPacketId() uint32 {
	if x != nil {
		return x.PacketId
	}
	return 0
}

func (x *DeliveryMetadata) GetQos() uint32 {
	if x != nil {
		return x.Qos
	}
	return 0
}

func (x *DeliveryMetadata) GetInflightDirection() uint32 {
	if x != nil {
		return x.InflightDirection
	}
	return 0
}

func (x *DeliveryMetadata) GetInflightState() uint32 {
	if x != nil {
		return x.InflightState
	}
	return 0
}

func (x *DeliveryMetadata) GetRetain() bool {
	if x != nil {
		return x.Retain
	}
	return false
}

func (x *DeliveryMetadata) GetDuplicate() bool {
	if x != nil {
		return x.Duplicate
	}
	return false
}

// QueueMetadata is the durable-queue lifecycle of a record.
type QueueMetadata struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Name    string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	GroupId string                 `protobuf:"bytes,3,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Offset  uint64                 `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	// state is a string rather than an enum, as protocol is; see SourceMetadata.
	State       string `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	CreatedAt   int64  `protobuf:"zigzag64,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	DeliveredAt int64  `protobuf:"zigzag64,7,opt,name=delivered_at,json=deliveredAt,proto3" json:"delivered_at,omitempty"`
	NextRetryAt int64  `protobuf:"zigzag64,8,opt,name=next_retry_at,json=nextRetryAt,proto3" json:"next_retry_at,omitempty"`
	RetryCount  uint32 `protobuf:"varint,9,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	ExpiresAt   int64  `protobuf:"zigzag64,10,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// stream is present only for a record in a stream-mode consumer group, which
	// is why it is a message rather than inline fields: absent and zeroed are
	// different states.
	Stream        *StreamMetadata `protobuf:"bytes,11,opt,name=stream,proto3" json:"stream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueMetadata) Reset() {
	*x = QueueMetadata{}
	mi := &file_message_v1_envelope_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueMetadata) ProtoMessage() {}

func (x *QueueMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_message_v1_envelope_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueMetadata.ProtoReflect.Descriptor instead.
func (*QueueMetadata) Descriptor() ([]byte, []int) {
	return file_message_v1_envelope_proto_rawDescGZIP(), []int{5}
}

func (x *QueueMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *QueueMetadata) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *QueueMetadata) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *QueueMetadata) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *QueueMetadata) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *QueueMetadata) GetDeliveredAt() int64 {
	if x != nil {
		return x.DeliveredAt
	}
	return 0
}

func (x *QueueMetadata) GetNextRetryAt() int64 {
	if x != nil {
		return x.NextRetryAt
	}
	return 0
}

func (x *QueueMetadata) GetRetryCount() uint32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *QueueMetadata) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *QueueMetadata) GetStream() *StreamMetadata {
	if x != nil {
		return x.Stream
	}
	return nil
}

// StreamMetadata is the stream-mode projection of a record.
type StreamMetadata struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Offset          uint64                 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Timestamp       int64                  `protobuf:"zigzag64,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	CommittedOffset uint64                 `protobuf:"varint,3,opt,name=committed_offset,json=committedOffset,proto3" json:"committed_offset,omitempty"`
	// has_committed_offset distinguishes a group that has committed offset 0 from
	// one that has committed nothing.
	HasCommittedOffset bool   `protobuf:"varint,4,opt,name=has_committed_offset,json=hasCommittedOffset,proto3" json:"has_committed_offset,omitempty"`
	WorkAcknowledged   bool   `protobuf:"varint,5,opt,name=work_acknowledged,json=workAcknowledged,proto3" json:"work_acknowledged,omitempty"`
	WorkGroup          string `protobuf:"bytes,6,opt,name=work_group,json=workGroup,proto3" json:"work_group,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StreamMetadata) Reset() {
	*x = StreamMetadata{}
	mi := &file_message_v1_envelope_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMetadata) ProtoMessage() {}

func (x *StreamMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_message_v1_envelope_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMetadata.ProtoReflect.Descriptor instead.
func (*StreamMetadata) Descriptor() ([]byte, []int) {
	return file_message_v1_envelope_proto_rawDescGZIP(), []int{6}
}

func (x *StreamMetadata) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *StreamMetadata) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *StreamMetadata) GetCommittedOffset() uint64 {
	if x != nil {
		return x.CommittedOffset
	}
	return 0
}

func (x *StreamMetadata) GetHasCommittedOffset() bool {
	if x != nil {
		return x.HasCommittedOffset
	}
	return false
}

func (x *StreamMetadata) GetWorkAcknowledged() bool {
	if x != nil {
		return x.WorkAcknowledged
	}
	return false
}

func (x *StreamMetadata) GetWorkGroup() string {
	if x != nil {
		return x.WorkGroup
	}
	return ""
}

// TransferMetadata records a recoverable broker-owned transfer, such as a move
// to a dead-letter queue.
type TransferMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the stable identity a dead-letter transfer is deduplicated by.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FailureReason string `protobuf:"bytes,2,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
	FirstAttempt  int64  `protobuf:"zigzag64,3,opt,name=first_attempt,json=firstAttempt,proto3" json:"first_attempt,omitempty"`
	LastAttempt   int64  `protobuf:"zigzag64,4,opt,name=last_attempt,json=lastAttempt,proto3" json:"last_attempt,omitempty"`
	CompletedAt   int64  `protobuf:"zigzag64,5,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	SourceQueue   string `protobuf:"bytes,6,opt,name=source_queue,json=sourceQueue,proto3" json:"source_queue,omitempty"`
	SourceGroup   string `protobuf:"bytes,7,opt,name=source_group,json=sourceGroup,proto3" json:"source_group,omitempty"`
	SourceOffset  uint64 `protobuf:"varint,8,opt,name=source_offset,json=sourceOffset,proto3" json:"source_offset,omitempty"`
	DeliveryCount uint32 `protobuf:"varint,9,opt,name=delivery_count,json=deliveryCount,proto3" json:"delivery_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferMetadata) Reset() {
	*x = TransferMetadata{}
	mi := &file_message_v1_envelope_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferMetadata) ProtoMessage() {}

func (x *TransferMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_message_v1_envelope_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferMetadata.ProtoReflect.Descriptor instead.
func (*TransferMetadata) Descriptor() ([]byte, []int) {
	return file_message_v1_envelope_proto_rawDescGZIP(), []int{7}
}

func (x *TransferMetadata) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TransferMetadata) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

func (x *TransferMetadata) GetFirstAttempt() int64 {
	if x != nil {
		return x.FirstAttempt
	}
	return 0
}

func (x *TransferMetadata) GetLastAttempt() int64 {
	if x != nil {
		return x.LastAttempt
	}
	return 0
}

func (x *TransferMetadata) GetCompletedAt() int64 {
	if x != nil {
		return x.CompletedAt
	}
	return 0
}

func (x *TransferMetadata) GetSourceQueue() string {
	if x != nil {
		return x.SourceQueue
	}
	return ""
}

func (x *TransferMetadata) GetSourceGroup() string {
	if x != nil {
		return x.SourceGroup
	}
	return ""
}

func (x *TransferMetadata) GetSourceOffset() uint64 {
	if x != nil {
		return x.SourceOffset
	}
	return 0
}

func (x *TransferMetadata) GetDeliveryCount() uint32 {
	if x != nil {
		return x.DeliveryCount
	}
	return 0
}

// TraceMetadata carries W3C trace context across broker hops.
type TraceMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceParent   string                 `protobuf:"bytes,1,opt,name=trace_parent,json=traceParent,proto3" json:"trace_parent,omitempty"`
	TraceState    string                 `protobuf:"bytes,2,opt,name=trace_state,json=traceState,proto3" json:"trace_state,omitempty"`
	TraceId       string                 `protobuf:"bytes,3,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TraceMetadata) Reset() {
	*x = TraceMetadata{}
	mi := &file_message_v1_envelope_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraceMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceMetadata) ProtoMessage() {}

func (x *TraceMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_message_v1_envelope_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceMetadata.ProtoReflect.Descriptor instead.
func (*TraceMetadata) Descriptor() ([]byte, []int) {
	return file_message_v1_envelope_proto_rawDescGZIP(), []int{8}
}

func (x *TraceMetadata) GetTraceParent() string {
	if x != nil {
		return x.TraceParent
	}
	return ""
}

func (x *TraceMetadata) GetTraceState() string {
	if x != nil {
		return x.TraceState
	}
	return ""
}

func (x *TraceMetadata) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

var File_message_v1_envelope_proto protoreflect.FileDescriptor

const file_message_v1_envelope_proto_rawDesc = "" +
	"\n" +
	"\x19message/v1/envelope.proto\x12\n" +
	"message.v1\"\xc5\x01\n" +
	"\bEnvelope\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12;\n" +
	"\tpublisher\x18\x04 \x01(\v2\x1d.message.v1.PublisherMetadataR\tpublisher\x122\n" +
	"\x06broker\x18\x05 \x01(\v2\x1a.message.v1.BrokerMetadataR\x06broker\"\xf2\x04\n" +
	"\x11PublisherMetadata\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12D\n" +
	"\aheaders\x18\x02 \x03(\v2*.message.v1.PublisherMetadata.HeadersEntryR\aheaders\x12M\n" +
	"\n" +
	"properties\x18\x03 \x03(\v2-.message.v1.PublisherMetadata.PropertiesEntryR\n" +
	"properties\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\x12)\n" +
	"\x10content_encoding\x18\x05 \x01(\tR\x0fcontentEncoding\x12%\n" +
	"\x0eresponse_topic\x18\x06 \x01(\tR\rresponseTopic\x12)\n" +
	"\x10correlation_data\x18\a \x01(\fR\x0fcorrelationData\x12*\n" +
	"\x0epayload_format\x18\b \x01(\rH\x00R\rpayloadFormat\x88\x01\x01\x12*\n" +
	"\x0emessage_expiry\x18\t \x01(\rH\x01R\rmessageExpiry\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"message_id\x18\n" +
	" \x01(\tR\tmessageId\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x11\n" +
	"\x0f_payload_formatB\x11\n" +
	"\x0f_message_expiry\"\x9a\x02\n" +
	"\x0eBrokerMetadata\x122\n" +
	"\x06source\x18\x01 \x01(\v2\x1a.message.v1.SourceMetadataR\x06source\x128\n" +
	"\bdelivery\x18\x02 \x01(\v2\x1c.message.v1.DeliveryMetadataR\bdelivery\x12/\n" +
	"\x05queue\x18\x03 \x01(\v2\x19.message.v1.QueueMetadataR\x05queue\x128\n" +
	"\btransfer\x18\x04 \x01(\v2\x1c.message.v1.TransferMetadataR\btransfer\x12/\n" +
	"\x05trace\x18\x05 \x01(\v2\x19.message.v1.TraceMetadataR\x05trace\"\x80\x01\n" +
	"\x0eSourceMetadata\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1f\n" +
	"\vexternal_id\x18\x02 \x01(\tR\n" +
	"externalId\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\x12\x14\n" +
	"\x05topic\x18\x04 \x01(\tR\x05topic\"\xbe\x02\n" +
	"\x10DeliveryMetadata\x12!\n" +
	"\fpublished_at\x18\x01 \x01(\x12R\vpublishedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\x12R\texpiresAt\x12-\n" +
	"\x10subscription_ids\x18\x03 \x03(\rB\x02\x10\x00R\x0fsubscriptionIds\x12\x1b\n" +
	"\tpacket_id\x18\x04 \x01(\rR\bpacketId\x12\x10\n" +
	"\x03qos\x18\x05 \x01(\rR\x03qos\x12-\n" +
	"\x12inflight_direction\x18\x06 \x01(\rR\x11inflightDirection\x12%\n" +
	"\x0einflight_state\x18\a \x01(\rR\rinflightState\x12\x16\n" +
	"\x06retain\x18\b \x01(\bR\x06retain\x12\x1c\n" +
	"\tduplicate\x18\t \x01(\bR\tduplicate\"\xd8\x02\n" +
	"\rQueueMetadata\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\bgroup_id\x18\x03 \x01(\tR\agroupId\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x04R\x06offset\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x12R\tcreatedAt\x12!\n" +
	"\fdelivered_at\x18\a \x01(\x12R\vdeliveredAt\x12\"\n" +
	"\rnext_retry_at\x18\b \x01(\x12R\vnextRetryAt\x12\x1f\n" +
	"\vretry_count\x18\t \x01(\rR\n" +
	"retryCount\x12\x1d\n" +
	"\n" +
	"expires_at\x18\n" +
	" \x01(\x12R\texpiresAt\x122\n" +
	"\x06stream\x18\v \x01(\v2\x1a.message.v1.StreamMetadataR\x06streamJ\x04\b\x01\x10\x02R\n" +
	"message_id\"\xef\x01\n" +
	"\x0eStreamMetadata\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x04R\x06offset\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x12R\ttimestamp\x12)\n" +
	"\x10committed_offset\x18\x03 \x01(\x04R\x0fcommittedOffset\x120\n" +
	"\x14has_committed_offset\x18\x04 \x01(\bR\x12hasCommittedOffset\x12+\n" +
	"\x11work_acknowledged\x18\x05 \x01(\bR\x10workAcknowledged\x12\x1d\n" +
	"\n" +
	"work_group\x18\x06 \x01(\tR\tworkGroup\"\xc6\x02\n" +
	"\x10TransferMetadata\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0efailure_reason\x18\x02 \x01(\tR\rfailureReason\x12#\n" +
	"\rfirst_attempt\x18\x03 \x01(\x12R\ffirstAttempt\x12!\n" +
	"\flast_attempt\x18\x04 \x01(\x12R\vlastAttempt\x12!\n" +
	"\fcompleted_at\x18\x05 \x01(\x12R\vcompletedAt\x12!\n" +
	"\fsource_queue\x18\x06 \x01(\tR\vsourceQueue\x12!\n" +
	"\fsource_group\x18\a \x01(\tR\vsourceGroup\x12#\n" +
	"\rsource_offset\x18\b \x01(\x04R\fsourceOffset\x12%\n" +
	"\x0edelivery_count\x18\t \x01(\rR\rdeliveryCount\"n\n" +
	"\rTraceMetadata\x12!\n" +
	"\ftrace_parent\x18\x01 \x01(\tR\vtraceParent\x12\x1f\n" +
	"\vtrace_state\x18\x02 \x01(\tR\n" +
	"traceState\x12\x19\n" +
	"\btrace_id\x18\x03 \x01(\tR\atraceIdB\xa2\x01\n" +
	"\x0ecom.message.v1B\rEnvelopeProtoP\x01Z8github.com/absmach/fluxmq/pkg/proto/message/v1;messagev1\xa2\x02\x03MXX\xaa\x02\n" +
	"Message.V1\xca\x02\n" +
	"Message\\V1\xe2\x02\x16Message\\V1\\GPBMetadata\xea\x02\vMessage::V1b\x06proto3"

var (
	file_message_v1_envelope_proto_rawDescOnce sync.Once
	file_message_v1_envelope_proto_rawDescData []byte
)

func file_message_v1_envelope_proto_rawDescGZIP() []byte {
	file_message_v1_envelope_proto_rawDescOnce.Do(func() {
		file_message_v1_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_v1_envelope_proto_rawDesc), len(file_message_v1_envelope_proto_rawDesc)))
	})
	return file_message_v1_envelope_proto_rawDescData
}

var file_message_v1_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_message_v1_envelope_proto_goTypes = []any{
	(*Envelope)(nil),          // 0: message.v1.Envelope
	(*PublisherMetadata)(nil), // 1: message.v1.PublisherMetadata
	(*BrokerMetadata)(nil),    // 2: message.v1.BrokerMetadata
	(*SourceMetadata)(nil),    // 3: message.v1.SourceMetadata
	(*DeliveryMetadata)(nil),  // 4: message.v1.DeliveryMetadata
	(*QueueMetadata)(nil),     // 5: message.v1.QueueMetadata
	(*StreamMetadata)(nil),    // 6: message.v1.StreamMetadata
	(*TransferMetadata)(nil),  // 7: message.v1.TransferMetadata
	(*TraceMetadata)(nil),     // 8: message.v1.TraceMetadata
	nil,                       // 9: message.v1.PublisherMetadata.HeadersEntry
	nil,                       // 10: message.v1.PublisherMetadata.PropertiesEntry
}
var file_message_v1_envelope_proto_depIdxs = []int32{
	1,  // 0: message.v1.Envelope.publisher:type_name -> message.v1.PublisherMetadata
	2,  // 1: message.v1.Envelope.broker:type_name -> message.v1.BrokerMetadata
	9,  // 2: message.v1.PublisherMetadata.headers:type_name -> message.v1.PublisherMetadata.HeadersEntry
	10, // 3: message.v1.PublisherMetadata.properties:type_name -> message.v1.PublisherMetadata.PropertiesEntry
	3,  // 4: message.v1.BrokerMetadata.source:type_name -> message.v1.SourceMetadata
	4,  // 5: message.v1.BrokerMetadata.delivery:type_name -> message.v1.DeliveryMetadata
	5,  // 6: message.v1.BrokerMetadata.queue:type_name -> message.v1.QueueMetadata
	7,  // 7: message.v1.BrokerMetadata.transfer:type_name -> message.v1.TransferMetadata
	8,  // 8: message.v1.BrokerMetadata.trace:type_name -> message.v1.TraceMetadata
	6,  // 9: message.v1.QueueMetadata.stream:type_name -> message.v1.StreamMetadata
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_message_v1_envelope_proto_init() }
func file_message_v1_envelope_proto_init() {
	if File_message_v1_envelope_proto != nil {
		return
	}
	file_message_v1_envelope_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_v1_envelope_proto_rawDesc), len(file_message_v1_envelope_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_v1_envelope_proto_goTypes,
		DependencyIndexes: file_message_v1_envelope_proto_depIdxs,
		MessageInfos:      file_message_v1_envelope_proto_msgTypes,
	}.Build()
	File_message_v1_envelope_proto = out.File
	file_message_v1_envelope_proto_goTypes = nil
	file_message_v1_envelope_proto_depIdxs = nil
}
