// Copyright (c) Abstract Machines
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: atom/v1/atom.proto

package atomv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SubjectId string                 `protobuf:"bytes,1,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	Action    string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"` // capability name, e.g. "publish"
	// Legacy form: identifies a row in the `resources` table. Resolved with
	// kind = `resources.kind`. Mutually exclusive with object_kind/object_id;
	// if both are supplied, object_kind/object_id win.
	ResourceId string `protobuf:"bytes,3,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	// Optional ABAC context - flat string key/value pairs injected into the
	// evaluation context under the "context" key.
	// Note: only string values are supported over gRPC; use REST for nested JSON.
	Context map[string]string `protobuf:"bytes,4,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Explicit form: identifies any first-class protected object.
	// Supported object_kind values: "resource" (same as resource_id) or
	// "tenant" (resolved from the `tenants` table; kind = "tenant").
	// Both fields must be set together, or both empty.
	ObjectKind    string `protobuf:"bytes,5,opt,name=object_kind,json=objectKind,proto3" json:"object_kind,omitempty"`
	ObjectId      string `protobuf:"bytes,6,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	mi := &file_atom_v1_atom_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atom_v1_atom_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_atom_v1_atom_proto_rawDescGZIP(), []int{0}
}

func (x *CheckRequest) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *CheckRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *CheckRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *CheckRequest) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *CheckRequest) GetObjectKind() string {
	if x != nil {
		return x.ObjectKind
	}
	return ""
}

func (x *CheckRequest) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

type CheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	mi := &file_atom_v1_atom_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atom_v1_atom_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_atom_v1_atom_proto_rawDescGZIP(), []int{1}
}

func (x *CheckResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *CheckResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type AuthenticateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JWT ("eyJ...") or API key ("atom_...") - same as the HTTP Bearer value.
	Token         string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateRequest) Reset() {
	*x = AuthenticateRequest{}
	mi := &file_atom_v1_atom_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateRequest) ProtoMessage() {}

func (x *AuthenticateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atom_v1_atom_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateRequest.ProtoReflect.Descriptor instead.
func (*AuthenticateRequest) Descriptor() ([]byte, []int) {
	return file_atom_v1_atom_proto_rawDescGZIP(), []int{2}
}

func (x *AuthenticateRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type AuthenticateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`    // empty string if entity has no tenant
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // empty string for API key authentication
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateResponse) Reset() {
	*x = AuthenticateResponse{}
	mi := &file_atom_v1_atom_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateResponse) ProtoMessage() {}

func (x *AuthenticateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atom_v1_atom_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateResponse.ProtoReflect.Descriptor instead.
func (*AuthenticateResponse) Descriptor() ([]byte, []int) {
	return file_atom_v1_atom_proto_rawDescGZIP(), []int{3}
}

func (x *AuthenticateResponse) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *AuthenticateResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *AuthenticateResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type AuthenticateCredentialRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Username-style identifier supplied by protocol adapters such as MQTT
	// brokers. For password credentials this may be an entity UUID, email, name,
	// or a tenant-scoped entity alias.
	Identifier string `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	// Plaintext secret supplied by the caller. Atom only stores its hash.
	Secret string `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	// Empty is treated as "password" for MQTT ergonomics.
	Kind          string `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	TenantId      string `protobuf:"bytes,4,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	TenantAlias   string `protobuf:"bytes,5,opt,name=tenant_alias,json=tenantAlias,proto3" json:"tenant_alias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateCredentialRequest) Reset() {
	*x = AuthenticateCredentialRequest{}
	mi := &file_atom_v1_atom_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateCredentialRequest) ProtoMessage() {}

func (x *AuthenticateCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atom_v1_atom_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateCredentialRequest.ProtoReflect.Descriptor instead.
func (*AuthenticateCredentialRequest) Descriptor() ([]byte, []int) {
	return file_atom_v1_atom_proto_rawDescGZIP(), []int{4}
}

func (x *AuthenticateCredentialRequest) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *AuthenticateCredentialRequest) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *AuthenticateCredentialRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *AuthenticateCredentialRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *AuthenticateCredentialRequest) GetTenantAlias() string {
	if x != nil {
		return x.TenantAlias
	}
	return ""
}

type AuthenticateCredentialResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	CredentialId  string                 `protobuf:"bytes,3,opt,name=credential_id,json=credentialId,proto3" json:"credential_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateCredentialResponse) Reset() {
	*x = AuthenticateCredentialResponse{}
	mi := &file_atom_v1_atom_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateCredentialResponse) ProtoMessage() {}

func (x *AuthenticateCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atom_v1_atom_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateCredentialResponse.ProtoReflect.Descriptor instead.
func (*AuthenticateCredentialResponse) Descriptor() ([]byte, []int) {
	return file_atom_v1_atom_proto_rawDescGZIP(), []int{5}
}

func (x *AuthenticateCredentialResponse) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *AuthenticateCredentialResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *AuthenticateCredentialResponse) GetCredentialId() string {
	if x != nil {
		return x.CredentialId
	}
	return ""
}

type ResolveCertificateRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SerialNumber      string                 `protobuf:"bytes,1,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	FingerprintSha256 string                 `protobuf:"bytes,2,opt,name=fingerprint_sha256,json=fingerprintSha256,proto3" json:"fingerprint_sha256,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ResolveCertificateRequest) Reset() {
	*x = ResolveCertificateRequest{}
	mi := &file_atom_v1_atom_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveCertificateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveCertificateRequest) ProtoMessage() {}

func (x *ResolveCertificateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atom_v1_atom_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveCertificateRequest.ProtoReflect.Descriptor instead.
func (*ResolveCertificateRequest) Descriptor() ([]byte, []int) {
	return file_atom_v1_atom_proto_rawDescGZIP(), []int{6}
}

func (x *ResolveCertificateRequest) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *ResolveCertificateRequest) GetFingerprintSha256() string {
	if x != nil {
		return x.FingerprintSha256
	}
	return ""
}

type ResolveCertificateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	CredentialId  string                 `protobuf:"bytes,3,opt,name=credential_id,json=credentialId,proto3" json:"credential_id,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveCertificateResponse) Reset() {
	*x = ResolveCertificateResponse{}
	mi := &file_atom_v1_atom_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveCertificateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveCertificateResponse) ProtoMessage() {}

func (x *ResolveCertificateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atom_v1_atom_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveCertificateResponse.ProtoReflect.Descriptor instead.
func (*ResolveCertificateResponse) Descriptor() ([]byte, []int) {
	return file_atom_v1_atom_proto_rawDescGZIP(), []int{7}
}

func (x *ResolveCertificateResponse) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *ResolveCertificateResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ResolveCertificateResponse) GetCredentialId() string {
	if x != nil {
		return x.CredentialId
	}
	return ""
}

func (x *ResolveCertificateResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

type RevokeEntityCertificatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeEntityCertificatesRequest) Reset() {
	*x = RevokeEntityCertificatesRequest{}
	mi := &file_atom_v1_atom_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeEntityCertificatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeEntityCertificatesRequest) ProtoMessage() {}

func (x *RevokeEntityCertificatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atom_v1_atom_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeEntityCertificatesRequest.ProtoReflect.Descriptor instead.
func (*RevokeEntityCertificatesRequest) Descriptor() ([]byte, []int) {
	return file_atom_v1_atom_proto_rawDescGZIP(), []int{8}
}

func (x *RevokeEntityCertificatesRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *RevokeEntityCertificatesRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RevokeEntityCertificatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revoked       uint64                 `protobuf:"varint,1,opt,name=revoked,proto3" json:"revoked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeEntityCertificatesResponse) Reset() {
	*x = RevokeEntityCertificatesResponse{}
	mi := &file_atom_v1_atom_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeEntityCertificatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeEntityCertificatesResponse) ProtoMessage() {}

func (x *RevokeEntityCertificatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atom_v1_atom_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeEntityCertificatesResponse.ProtoReflect.Descriptor instead.
func (*RevokeEntityCertificatesResponse) Descriptor() ([]byte, []int) {
	return file_atom_v1_atom_proto_rawDescGZIP(), []int{9}
}

func (x *RevokeEntityCertificatesResponse) GetRevoked() uint64 {
	if x != nil {
		return x.Revoked
	}
	return 0
}

type ResolveAliasRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tenant selector - exactly one of tenant_id, tenant_alias, or global must
	// be set. tenant_alias is the case-folded tenant slug.
	TenantId    string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	TenantAlias string `protobuf:"bytes,2,opt,name=tenant_alias,json=tenantAlias,proto3" json:"tenant_alias,omitempty"`
	// Which table the object alias addresses: "entity" (clients/devices) or
	// "resource" (channels). Other values are rejected. Generic on purpose -
	// no domain/channel vocabulary.
	ObjectKind string `protobuf:"bytes,3,opt,name=object_kind,json=objectKind,proto3" json:"object_kind,omitempty"`
	// The object's alias slug, unique within the tenant.
	ObjectAlias string `protobuf:"bytes,4,opt,name=object_alias,json=objectAlias,proto3" json:"object_alias,omitempty"`
	// Resolve an entity or resource whose tenant_id is NULL.
	Global        bool `protobuf:"varint,5,opt,name=global,proto3" json:"global,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveAliasRequest) Reset() {
	*x = ResolveAliasRequest{}
	mi := &file_atom_v1_atom_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveAliasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveAliasRequest) ProtoMessage() {}

func (x *ResolveAliasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atom_v1_atom_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveAliasRequest.ProtoReflect.Descriptor instead.
func (*ResolveAliasRequest) Descriptor() ([]byte, []int) {
	return file_atom_v1_atom_proto_rawDescGZIP(), []int{10}
}

func (x *ResolveAliasRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ResolveAliasRequest) GetTenantAlias() string {
	if x != nil {
		return x.TenantAlias
	}
	return ""
}

func (x *ResolveAliasRequest) GetObjectKind() string {
	if x != nil {
		return x.ObjectKind
	}
	return ""
}

func (x *ResolveAliasRequest) GetObjectAlias() string {
	if x != nil {
		return x.ObjectAlias
	}
	return ""
}

func (x *ResolveAliasRequest) GetGlobal() bool {
	if x != nil {
		return x.Global
	}
	return false
}

type ResolveAliasResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"` // empty string for global objects
	ObjectId      string                 `protobuf:"bytes,2,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveAliasResponse) Reset() {
	*x = ResolveAliasResponse{}
	mi := &file_atom_v1_atom_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveAliasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveAliasResponse) ProtoMessage() {}

func (x *ResolveAliasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atom_v1_atom_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveAliasResponse.ProtoReflect.Descriptor instead.
func (*ResolveAliasResponse) Descriptor() ([]byte, []int) {
	return file_atom_v1_atom_proto_rawDescGZIP(), []int{11}
}

func (x *ResolveAliasResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ResolveAliasResponse) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

var File_atom_v1_atom_proto protoreflect.FileDescriptor

const file_atom_v1_atom_proto_rawDesc = "" +
	"\n" +
	"\x12atom/v1/atom.proto\x12\aatom.v1\"\x9e\x02\n" +
	"\fCheckRequest\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x01 \x01(\tR\tsubjectId\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x1f\n" +
	"\vresource_id\x18\x03 \x01(\tR\n" +
	"resourceId\x12<\n" +
	"\acontext\x18\x04 \x03(\v2\".atom.v1.CheckRequest.ContextEntryR\acontext\x12\x1f\n" +
	"\vobject_kind\x18\x05 \x01(\tR\n" +
	"objectKind\x12\x1b\n" +
	"\tobject_id\x18\x06 \x01(\tR\bobjectId\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"A\n" +
	"\rCheckResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"+\n" +
	"\x13AuthenticateRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"o\n" +
	"\x14AuthenticateResponse\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\"\xab\x01\n" +
	"\x1dAuthenticateCredentialRequest\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x01(\tR\n" +
	"identifier\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\tR\x06secret\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x1b\n" +
	"\ttenant_id\x18\x04 \x01(\tR\btenantId\x12!\n" +
	"\ftenant_alias\x18\x05 \x01(\tR\vtenantAlias\"\x7f\n" +
	"\x1eAuthenticateCredentialResponse\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12#\n" +
	"\rcredential_id\x18\x03 \x01(\tR\fcredentialId\"o\n" +
	"\x19ResolveCertificateRequest\x12#\n" +
	"\rserial_number\x18\x01 \x01(\tR\fserialNumber\x12-\n" +
	"\x12fingerprint_sha256\x18\x02 \x01(\tR\x11fingerprintSha256\"\x9a\x01\n" +
	"\x1aResolveCertificateResponse\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12#\n" +
	"\rcredential_id\x18\x03 \x01(\tR\fcredentialId\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\tR\texpiresAt\"V\n" +
	"\x1fRevokeEntityCertificatesRequest\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"<\n" +
	" RevokeEntityCertificatesResponse\x12\x18\n" +
	"\arevoked\x18\x01 \x01(\x04R\arevoked\"\xb1\x01\n" +
	"\x13ResolveAliasRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12!\n" +
	"\ftenant_alias\x18\x02 \x01(\tR\vtenantAlias\x12\x1f\n" +
	"\vobject_kind\x18\x03 \x01(\tR\n" +
	"objectKind\x12!\n" +
	"\fobject_alias\x18\x04 \x01(\tR\vobjectAlias\x12\x16\n" +
	"\x06global\x18\x05 \x01(\bR\x06global\"P\n" +
	"\x14ResolveAliasResponse\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1b\n" +
	"\tobject_id\x18\x02 \x01(\tR\bobjectId2F\n" +
	"\fAuthzService\x126\n" +
	"\x05Check\x12\x15.atom.v1.CheckRequest\x1a\x16.atom.v1.CheckResponse2\xc5\x01\n" +
	"\vAuthService\x12K\n" +
	"\fAuthenticate\x12\x1c.atom.v1.AuthenticateRequest\x1a\x1d.atom.v1.AuthenticateResponse\x12i\n" +
	"\x16AuthenticateCredential\x12&.atom.v1.AuthenticateCredentialRequest\x1a'.atom.v1.AuthenticateCredentialResponse2\xe4\x01\n" +
	"\x12CertificateService\x12]\n" +
	"\x12ResolveCertificate\x12\".atom.v1.ResolveCertificateRequest\x1a#.atom.v1.ResolveCertificateResponse\x12o\n" +
	"\x18RevokeEntityCertificates\x12(.atom.v1.RevokeEntityCertificatesRequest\x1a).atom.v1.RevokeEntityCertificatesResponse2[\n" +
	"\fAliasService\x12K\n" +
	"\fResolveAlias\x12\x1c.atom.v1.ResolveAliasRequest\x1a\x1d.atom.v1.ResolveAliasResponseB\x89\x01\n" +
	"\vcom.atom.v1B\tAtomProtoP\x01Z2github.com/absmach/fluxmq/pkg/proto/atom/v1;atomv1\xa2\x02\x03AXX\xaa\x02\aAtom.V1\xca\x02\aAtom\\V1\xe2\x02\x13Atom\\V1\\GPBMetadata\xea\x02\bAtom::V1b\x06proto3"

var (
	file_atom_v1_atom_proto_rawDescOnce sync.Once
	file_atom_v1_atom_proto_rawDescData []byte
)

func file_atom_v1_atom_proto_rawDescGZIP() []byte {
	file_atom_v1_atom_proto_rawDescOnce.Do(func() {
		file_atom_v1_atom_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_atom_v1_atom_proto_rawDesc), len(file_atom_v1_atom_proto_rawDesc)))
	})
	return file_atom_v1_atom_proto_rawDescData
}

var file_atom_v1_atom_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_atom_v1_atom_proto_goTypes = []any{
	(*CheckRequest)(nil),                     // 0: atom.v1.CheckRequest
	(*CheckResponse)(nil),                    // 1: atom.v1.CheckResponse
	(*AuthenticateRequest)(nil),              // 2: atom.v1.AuthenticateRequest
	(*AuthenticateResponse)(nil),             // 3: atom.v1.AuthenticateResponse
	(*AuthenticateCredentialRequest)(nil),    // 4: atom.v1.AuthenticateCredentialRequest
	(*AuthenticateCredentialResponse)(nil),   // 5: atom.v1.AuthenticateCredentialResponse
	(*ResolveCertificateRequest)(nil),        // 6: atom.v1.ResolveCertificateRequest
	(*ResolveCertificateResponse)(nil),       // 7: atom.v1.ResolveCertificateResponse
	(*RevokeEntityCertificatesRequest)(nil),  // 8: atom.v1.RevokeEntityCertificatesRequest
	(*RevokeEntityCertificatesResponse)(nil), // 9: atom.v1.RevokeEntityCertificatesResponse
	(*ResolveAliasRequest)(nil),              // 10: atom.v1.ResolveAliasRequest
	(*ResolveAliasResponse)(nil),             // 11: atom.v1.ResolveAliasResponse
	nil,                                      // 12: atom.v1.CheckRequest.ContextEntry
}
var file_atom_v1_atom_proto_depIdxs = []int32{
	12, // 0: atom.v1.CheckRequest.context:type_name -> atom.v1.CheckRequest.ContextEntry
	0,  // 1: atom.v1.AuthzService.Check:input_type -> atom.v1.CheckRequest
	2,  // 2: atom.v1.AuthService.Authenticate:input_type -> atom.v1.AuthenticateRequest
	4,  // 3: atom.v1.AuthService.AuthenticateCredential:input_type -> atom.v1.AuthenticateCredentialRequest
	6,  // 4: atom.v1.CertificateService.ResolveCertificate:input_type -> atom.v1.ResolveCertificateRequest
	8,  // 5: atom.v1.CertificateService.RevokeEntityCertificates:input_type -> atom.v1.RevokeEntityCertificatesRequest
	10, // 6: atom.v1.AliasService.ResolveAlias:input_type -> atom.v1.ResolveAliasRequest
	1,  // 7: atom.v1.AuthzService.Check:output_type -> atom.v1.CheckResponse
	3,  // 8: atom.v1.AuthService.Authenticate:output_type -> atom.v1.AuthenticateResponse
	5,  // 9: atom.v1.AuthService.AuthenticateCredential:output_type -> atom.v1.AuthenticateCredentialResponse
	7,  // 10: atom.v1.CertificateService.ResolveCertificate:output_type -> atom.v1.ResolveCertificateResponse
	9,  // 11: atom.v1.CertificateService.RevokeEntityCertificates:output_type -> atom.v1.RevokeEntityCertificatesResponse
	11, // 12: atom.v1.AliasService.ResolveAlias:output_type -> atom.v1.ResolveAliasResponse
	7,  // [7:13] is the sub-list for method output_type
	1,  // [1:7] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_atom_v1_atom_proto_init() }
func file_atom_v1_atom_proto_init() {
	if File_atom_v1_atom_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_atom_v1_atom_proto_rawDesc), len(file_atom_v1_atom_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_atom_v1_atom_proto_goTypes,
		DependencyIndexes: file_atom_v1_atom_proto_depIdxs,
		MessageInfos:      file_atom_v1_atom_proto_msgTypes,
	}.Build()
	File_atom_v1_atom_proto = out.File
	file_atom_v1_atom_proto_goTypes = nil
	file_atom_v1_atom_proto_depIdxs = nil
}
