// Copyright (c) Abstract Machines
// SPDX-License-Identifier: Apache-2.0

package message

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/printer"
	"go/token"
	"os"
	"slices"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
)

var updateMessageAPIBaseline = flag.Bool("update-message-api-baseline", false,
	"rewrite the frozen message Go API baseline instead of comparing against it")

const messageAPIBaselinePath = "../api/compat/go-message-v1.txt"

var frozenMessageTypes = []string{
	"Version", "Protocol", "QueueState",
	"Binary", "HeaderMap", "PropertyMap", "Uint32List", "Optional",
	"PublisherMetadata", "SourceMetadata", "DeliveryMetadata", "StreamMetadata",
	"QueueMetadata", "TransferMetadata", "TraceMetadata", "BrokerMetadata",
	"Envelope", "Projection",
}

var frozenMessageFunctions = []string{
	"Acquire", "Release",
	"New", "NewDelivery", "NewWithBuffer",
	"NewBinary", "NewHeaderMap", "NewPropertyMap", "NewUint32List", "Some",
	"MarshalBinary", "MarshalMetadata", "UnmarshalBinary", "UnmarshalMetadata",
	"FilterUserProperties", "ApplyTrustedProperties", "ProjectProperties",
}

func TestFrozenMessageGoAPIMatchesBaseline(t *testing.T) {
	rendered := renderFrozenMessageAPI(t)
	if *updateMessageAPIBaseline {
		require.NoError(t, os.WriteFile(messageAPIBaselinePath, []byte(rendered), 0o644))
		t.Log("message API baseline rewritten; review the diff before committing")
		return
	}

	recorded, err := os.ReadFile(messageAPIBaselinePath)
	require.NoError(t, err,
		"run go test ./message -run TestFrozenMessageGoAPIMatchesBaseline -update-message-api-baseline to create it")
	require.Equal(t, string(recorded), rendered,
		"the frozen message API changed. If intended, refresh and review api/compat/go-message-v1.txt")
}

func renderFrozenMessageAPI(t *testing.T) string {
	t.Helper()
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, ".", func(info os.FileInfo) bool {
		return !strings.HasSuffix(info.Name(), "_test.go")
	}, 0)
	require.NoError(t, err)
	pkg := pkgs["message"]
	require.NotNil(t, pkg)

	types := map[string]*ast.TypeSpec{}
	constsByType := map[string][]string{}
	functions := map[string]*ast.FuncDecl{}
	methods := map[string][]*ast.FuncDecl{}
	for _, file := range pkg.Files {
		for _, decl := range file.Decls {
			switch declaration := decl.(type) {
			case *ast.GenDecl:
				for _, spec := range declaration.Specs {
					switch value := spec.(type) {
					case *ast.TypeSpec:
						types[value.Name.Name] = value
					case *ast.ValueSpec:
						typeName, rendered := renderMessageConst(fset, value)
						if typeName != "" {
							constsByType[typeName] = append(constsByType[typeName], rendered)
						}
					}
				}
			case *ast.FuncDecl:
				if declaration.Recv == nil {
					functions[declaration.Name.Name] = declaration
					continue
				}
				if name := receiverTypeName(declaration.Recv.List[0].Type); name != "" {
					methods[name] = append(methods[name], declaration)
				}
			}
		}
	}

	var out strings.Builder
	out.WriteString("# Frozen Go API - package message\n")
	out.WriteString("# Generated by TestFrozenMessageGoAPIMatchesBaseline. Do not edit by hand.\n")
	out.WriteString("# Private representation is omitted; exported fields and methods are the contract.\n\n")
	for _, name := range frozenMessageTypes {
		spec := types[name]
		require.NotNil(t, spec, "frozen type %q no longer exists", name)
		publicSpec := *spec
		publicSpec.Type = publicType(spec.Type)
		fmt.Fprintf(&out, "type %s\n", printNode(t, fset, &publicSpec))
		values := constsByType[name]
		slices.Sort(values)
		for _, value := range values {
			fmt.Fprintf(&out, "\tconst %s\n", value)
		}

		decls := methods[name]
		slices.SortFunc(decls, func(a, b *ast.FuncDecl) int {
			return strings.Compare(a.Name.Name, b.Name.Name)
		})
		for _, method := range decls {
			if method.Name.IsExported() {
				fmt.Fprintf(&out, "\t%s\n", printFuncDecl(t, fset, method))
			}
		}
		out.WriteString("\n")
	}

	out.WriteString("# Constructors and envelope boundary functions\n")
	for _, name := range frozenMessageFunctions {
		function := functions[name]
		require.NotNil(t, function, "frozen function %q no longer exists", name)
		fmt.Fprintf(&out, "%s\n", printFuncDecl(t, fset, function))
	}
	return out.String()
}

func publicType(expr ast.Expr) ast.Expr {
	structure, ok := expr.(*ast.StructType)
	if !ok {
		return expr
	}
	fields := make([]*ast.Field, 0, len(structure.Fields.List))
	for _, field := range structure.Fields.List {
		if len(field.Names) == 0 || field.Names[0].IsExported() {
			fields = append(fields, field)
		}
	}
	return &ast.StructType{Fields: &ast.FieldList{List: fields}}
}

func receiverTypeName(expr ast.Expr) string {
	switch value := expr.(type) {
	case *ast.Ident:
		return value.Name
	case *ast.StarExpr:
		return receiverTypeName(value.X)
	case *ast.IndexExpr:
		return receiverTypeName(value.X)
	case *ast.IndexListExpr:
		return receiverTypeName(value.X)
	default:
		return ""
	}
}

func printFuncDecl(t *testing.T, fset *token.FileSet, declaration *ast.FuncDecl) string {
	t.Helper()
	copy := *declaration
	copy.Body = nil
	return printNode(t, fset, &copy)
}

func printNode(t *testing.T, fset *token.FileSet, node any) string {
	t.Helper()
	var output bytes.Buffer
	require.NoError(t, printer.Fprint(&output, fset, node))
	return output.String()
}

func renderMessageConst(fset *token.FileSet, spec *ast.ValueSpec) (string, string) {
	ident, ok := spec.Type.(*ast.Ident)
	if !ok || len(spec.Names) == 0 || len(spec.Values) == 0 {
		return "", ""
	}
	var value bytes.Buffer
	if err := printer.Fprint(&value, fset, spec.Values[0]); err != nil {
		return "", ""
	}
	return ident.Name, spec.Names[0].Name + " = " + value.String()
}
