// Copyright (c) Abstract Machines
// SPDX-License-Identifier: Apache-2.0

package queue

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/printer"
	"go/token"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
)

var updateAPIBaseline = flag.Bool("update-api-baseline", false,
	"rewrite the frozen Go API baseline instead of comparing against it")

const apiBaselinePath = "../api/compat/go-queue-v1.txt"

// frozenTypes are the queue types API-COMPATIBILITY.md freezes: the command
// processor "and its typed command/outcome values".
//
// The compile-time guard in state_machine_api_compat_test.go pins the interface
// method set and nothing else — it names the live types, so a field added to a
// command, or an enum's underlying type changed, satisfies it unchanged. The
// SeekKind string-to-int change passed that guard, which is what this baseline
// exists to catch.
var frozenTypes = []string{
	"CommandProcessor",
	"OffsetCommitter",
	"AppendCommand", "AppendOutcome",
	"ConsumeCommand", "ConsumeOutcome",
	"CommitConsumeCommand", "CommitOffsetCommand",
	"AckCommand", "NackCommand", "RejectCommand", "SettlementOutcome",
	"ClaimCommand", "ClaimOutcome",
	"SeekKind", "SeekCommand", "SeekOutcome",
}

// The exported Go surface this package promises must change only deliberately.
//
// Run with -update-api-baseline to record an intended change; the diff is then
// reviewable in the same way api/compat/*.binpb is for protobuf.
func TestFrozenGoAPIMatchesBaseline(t *testing.T) {
	rendered := renderFrozenAPI(t)

	if *updateAPIBaseline {
		require.NoError(t, os.WriteFile(apiBaselinePath, []byte(rendered), 0o600))
		t.Log("baseline rewritten; review the diff before committing")
		return
	}

	recorded, err := os.ReadFile(apiBaselinePath)
	require.NoError(t, err, "run go test ./queue -update-api-baseline to create it")

	require.Equal(t, string(recorded), rendered,
		"the frozen queue API changed.\n"+
			"API-COMPATIBILITY.md freezes these types. Adding a field, renaming one, "+
			"or changing an enum's underlying type breaks every external caller. "+
			"If the change is intended, run:\n"+
			"  go test ./queue -run TestFrozenGoAPIMatchesBaseline -update-api-baseline\n"+
			"and put the baseline diff in the review.")
}

func renderFrozenAPI(t *testing.T) string {
	t.Helper()

	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, ".", func(info os.FileInfo) bool {
		return !strings.HasSuffix(info.Name(), "_test.go")
	}, 0)
	require.NoError(t, err)

	pkg, ok := pkgs["queue"]
	require.True(t, ok, "queue package not found in %s", mustAbs(t))

	types := map[string]*ast.TypeSpec{}
	constsByType := map[string][]string{}

	for _, file := range pkg.Files {
		for _, decl := range file.Decls {
			genDecl, ok := decl.(*ast.GenDecl)
			if !ok {
				continue
			}
			for _, spec := range genDecl.Specs {
				switch s := spec.(type) {
				case *ast.TypeSpec:
					types[s.Name.Name] = s
				case *ast.ValueSpec:
					name, value := renderConst(fset, s)
					if name == "" {
						continue
					}
					constsByType[name] = append(constsByType[name], value)
				}
			}
		}
	}

	var out strings.Builder
	out.WriteString("# Frozen Go API — package queue\n")
	out.WriteString("# Generated by TestFrozenGoAPIMatchesBaseline. Do not edit by hand.\n")
	out.WriteString("# See API-COMPATIBILITY.md; a diff here is a contract change.\n\n")

	for _, name := range frozenTypes {
		spec, found := types[name]
		require.True(t, found, "frozen type %q no longer exists", name)

		var buf bytes.Buffer
		require.NoError(t, printer.Fprint(&buf, fset, spec.Type))
		fmt.Fprintf(&out, "type %s %s\n", name, buf.String())

		values := constsByType[name]
		slices.Sort(values)
		for _, value := range values {
			fmt.Fprintf(&out, "\tconst %s\n", value)
		}
		out.WriteString("\n")
	}

	return out.String()
}

// renderConst reports the declared type and rendering of a typed constant, or
// an empty name when the spec is not one.
func renderConst(fset *token.FileSet, spec *ast.ValueSpec) (typeName, rendered string) {
	ident, ok := spec.Type.(*ast.Ident)
	if !ok || len(spec.Names) == 0 || len(spec.Values) == 0 {
		return "", ""
	}
	var buf bytes.Buffer
	if err := printer.Fprint(&buf, fset, spec.Values[0]); err != nil {
		return "", ""
	}
	return ident.Name, spec.Names[0].Name + " = " + buf.String()
}

func mustAbs(t *testing.T) string {
	t.Helper()
	dir, err := filepath.Abs(".")
	require.NoError(t, err)
	return dir
}
