// Copyright (c) Abstract Machines
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: auth/v1/auth.proto

package authv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/absmach/fluxmq/pkg/proto/auth/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AuthServiceName is the fully-qualified name of the AuthService service.
	AuthServiceName = "fluxmq.auth.v1.AuthService"
	// HookServiceName is the fully-qualified name of the HookService service.
	HookServiceName = "fluxmq.auth.v1.HookService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AuthServiceAuthenticateProcedure is the fully-qualified name of the AuthService's Authenticate
	// RPC.
	AuthServiceAuthenticateProcedure = "/fluxmq.auth.v1.AuthService/Authenticate"
	// AuthServiceAuthorizeProcedure is the fully-qualified name of the AuthService's Authorize RPC.
	AuthServiceAuthorizeProcedure = "/fluxmq.auth.v1.AuthService/Authorize"
	// HookServiceHandleProcedure is the fully-qualified name of the HookService's Handle RPC.
	HookServiceHandleProcedure = "/fluxmq.auth.v1.HookService/Handle"
)

// AuthServiceClient is a client for the fluxmq.auth.v1.AuthService service.
type AuthServiceClient interface {
	// Authenticate validates client credentials presented during connection.
	// The server resolves the credentials to an external identity (e.g. a UUID)
	// which the broker stores on the session and passes in subsequent Authorize
	// calls.
	Authenticate(context.Context, *connect.Request[v1.AuthnReq]) (*connect.Response[v1.AuthnRes], error)
	// Authorize checks whether a previously authenticated identity is allowed
	// to perform a given action on the effective topic/filter. When the optional
	// topic normalizer is configured, the broker authorizes the normalized value.
	Authorize(context.Context, *connect.Request[v1.AuthzReq]) (*connect.Response[v1.AuthzRes], error)
}

// NewAuthServiceClient constructs a client for the fluxmq.auth.v1.AuthService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAuthServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AuthServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	authServiceMethods := v1.File_auth_v1_auth_proto.Services().ByName("AuthService").Methods()
	return &authServiceClient{
		authenticate: connect.NewClient[v1.AuthnReq, v1.AuthnRes](
			httpClient,
			baseURL+AuthServiceAuthenticateProcedure,
			connect.WithSchema(authServiceMethods.ByName("Authenticate")),
			connect.WithClientOptions(opts...),
		),
		authorize: connect.NewClient[v1.AuthzReq, v1.AuthzRes](
			httpClient,
			baseURL+AuthServiceAuthorizeProcedure,
			connect.WithSchema(authServiceMethods.ByName("Authorize")),
			connect.WithClientOptions(opts...),
		),
	}
}

// authServiceClient implements AuthServiceClient.
type authServiceClient struct {
	authenticate *connect.Client[v1.AuthnReq, v1.AuthnRes]
	authorize    *connect.Client[v1.AuthzReq, v1.AuthzRes]
}

// Authenticate calls fluxmq.auth.v1.AuthService.Authenticate.
func (c *authServiceClient) Authenticate(ctx context.Context, req *connect.Request[v1.AuthnReq]) (*connect.Response[v1.AuthnRes], error) {
	return c.authenticate.CallUnary(ctx, req)
}

// Authorize calls fluxmq.auth.v1.AuthService.Authorize.
func (c *authServiceClient) Authorize(ctx context.Context, req *connect.Request[v1.AuthzReq]) (*connect.Response[v1.AuthzRes], error) {
	return c.authorize.CallUnary(ctx, req)
}

// AuthServiceHandler is an implementation of the fluxmq.auth.v1.AuthService service.
type AuthServiceHandler interface {
	// Authenticate validates client credentials presented during connection.
	// The server resolves the credentials to an external identity (e.g. a UUID)
	// which the broker stores on the session and passes in subsequent Authorize
	// calls.
	Authenticate(context.Context, *connect.Request[v1.AuthnReq]) (*connect.Response[v1.AuthnRes], error)
	// Authorize checks whether a previously authenticated identity is allowed
	// to perform a given action on the effective topic/filter. When the optional
	// topic normalizer is configured, the broker authorizes the normalized value.
	Authorize(context.Context, *connect.Request[v1.AuthzReq]) (*connect.Response[v1.AuthzRes], error)
}

// NewAuthServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAuthServiceHandler(svc AuthServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	authServiceMethods := v1.File_auth_v1_auth_proto.Services().ByName("AuthService").Methods()
	authServiceAuthenticateHandler := connect.NewUnaryHandler(
		AuthServiceAuthenticateProcedure,
		svc.Authenticate,
		connect.WithSchema(authServiceMethods.ByName("Authenticate")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceAuthorizeHandler := connect.NewUnaryHandler(
		AuthServiceAuthorizeProcedure,
		svc.Authorize,
		connect.WithSchema(authServiceMethods.ByName("Authorize")),
		connect.WithHandlerOptions(opts...),
	)
	return "/fluxmq.auth.v1.AuthService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AuthServiceAuthenticateProcedure:
			authServiceAuthenticateHandler.ServeHTTP(w, r)
		case AuthServiceAuthorizeProcedure:
			authServiceAuthorizeHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAuthServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAuthServiceHandler struct{}

func (UnimplementedAuthServiceHandler) Authenticate(context.Context, *connect.Request[v1.AuthnReq]) (*connect.Response[v1.AuthnRes], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("fluxmq.auth.v1.AuthService.Authenticate is not implemented"))
}

func (UnimplementedAuthServiceHandler) Authorize(context.Context, *connect.Request[v1.AuthzReq]) (*connect.Response[v1.AuthzRes], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("fluxmq.auth.v1.AuthService.Authorize is not implemented"))
}

// HookServiceClient is a client for the fluxmq.auth.v1.HookService service.
type HookServiceClient interface {
	Handle(context.Context, *connect.Request[v1.HookReq]) (*connect.Response[v1.HookRes], error)
}

// NewHookServiceClient constructs a client for the fluxmq.auth.v1.HookService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewHookServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) HookServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	hookServiceMethods := v1.File_auth_v1_auth_proto.Services().ByName("HookService").Methods()
	return &hookServiceClient{
		handle: connect.NewClient[v1.HookReq, v1.HookRes](
			httpClient,
			baseURL+HookServiceHandleProcedure,
			connect.WithSchema(hookServiceMethods.ByName("Handle")),
			connect.WithClientOptions(opts...),
		),
	}
}

// hookServiceClient implements HookServiceClient.
type hookServiceClient struct {
	handle *connect.Client[v1.HookReq, v1.HookRes]
}

// Handle calls fluxmq.auth.v1.HookService.Handle.
func (c *hookServiceClient) Handle(ctx context.Context, req *connect.Request[v1.HookReq]) (*connect.Response[v1.HookRes], error) {
	return c.handle.CallUnary(ctx, req)
}

// HookServiceHandler is an implementation of the fluxmq.auth.v1.HookService service.
type HookServiceHandler interface {
	Handle(context.Context, *connect.Request[v1.HookReq]) (*connect.Response[v1.HookRes], error)
}

// NewHookServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewHookServiceHandler(svc HookServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	hookServiceMethods := v1.File_auth_v1_auth_proto.Services().ByName("HookService").Methods()
	hookServiceHandleHandler := connect.NewUnaryHandler(
		HookServiceHandleProcedure,
		svc.Handle,
		connect.WithSchema(hookServiceMethods.ByName("Handle")),
		connect.WithHandlerOptions(opts...),
	)
	return "/fluxmq.auth.v1.HookService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case HookServiceHandleProcedure:
			hookServiceHandleHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedHookServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedHookServiceHandler struct{}

func (UnimplementedHookServiceHandler) Handle(context.Context, *connect.Request[v1.HookReq]) (*connect.Response[v1.HookRes], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("fluxmq.auth.v1.HookService.Handle is not implemented"))
}
