// Copyright (c) Abstract Machines
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: auth/v1/auth.proto

package authv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Action int32

const (
	Action_ACTION_PUBLISH   Action = 0
	Action_ACTION_SUBSCRIBE Action = 1
)

// Enum value maps for Action.
var (
	Action_name = map[int32]string{
		0: "ACTION_PUBLISH",
		1: "ACTION_SUBSCRIBE",
	}
	Action_value = map[string]int32{
		"ACTION_PUBLISH":   0,
		"ACTION_SUBSCRIBE": 1,
	}
)

func (x Action) Enum() *Action {
	p := new(Action)
	*p = x
	return p
}

func (x Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Action) Descriptor() protoreflect.EnumDescriptor {
	return file_auth_v1_auth_proto_enumTypes[0].Descriptor()
}

func (Action) Type() protoreflect.EnumType {
	return &file_auth_v1_auth_proto_enumTypes[0]
}

func (x Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Action.Descriptor instead.
func (Action) EnumDescriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{0}
}

type AuthnReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// MQTT ClientID from the CONNECT packet.
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// Username from the CONNECT packet.
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	// Password from the CONNECT packet.
	Password      string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthnReq) Reset() {
	*x = AuthnReq{}
	mi := &file_auth_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthnReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthnReq) ProtoMessage() {}

func (x *AuthnReq) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthnReq.ProtoReflect.Descriptor instead.
func (*AuthnReq) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *AuthnReq) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *AuthnReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AuthnReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AuthnRes struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the credentials are valid.
	Authenticated bool `protobuf:"varint,1,opt,name=authenticated,proto3" json:"authenticated,omitempty"`
	// External identity resolved by the auth provider (e.g. a client UUID).
	// The broker stores this on the session and passes it in AuthzReq.
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// Machine-readable reason code (0 = success).
	ReasonCode uint32 `protobuf:"varint,3,opt,name=reason_code,json=reasonCode,proto3" json:"reason_code,omitempty"`
	// Human-readable reason for rejection (empty on success).
	Reason        string `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthnRes) Reset() {
	*x = AuthnRes{}
	mi := &file_auth_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthnRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthnRes) ProtoMessage() {}

func (x *AuthnRes) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthnRes.ProtoReflect.Descriptor instead.
func (*AuthnRes) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *AuthnRes) GetAuthenticated() bool {
	if x != nil {
		return x.Authenticated
	}
	return false
}

func (x *AuthnRes) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AuthnRes) GetReasonCode() uint32 {
	if x != nil {
		return x.ReasonCode
	}
	return 0
}

func (x *AuthnRes) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type AuthzReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// External identity returned from AuthnRes.id.
	ExternalId string `protobuf:"bytes,1,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	// Raw topic or topic filter from the PUBLISH/SUBSCRIBE packet.
	Topic string `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	// The action being requested.
	Action        Action `protobuf:"varint,3,opt,name=action,proto3,enum=fluxmq.auth.v1.Action" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthzReq) Reset() {
	*x = AuthzReq{}
	mi := &file_auth_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthzReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthzReq) ProtoMessage() {}

func (x *AuthzReq) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthzReq.ProtoReflect.Descriptor instead.
func (*AuthzReq) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *AuthzReq) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *AuthzReq) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *AuthzReq) GetAction() Action {
	if x != nil {
		return x.Action
	}
	return Action_ACTION_PUBLISH
}

type AuthzRes struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the action is authorized.
	Authorized bool `protobuf:"varint,1,opt,name=authorized,proto3" json:"authorized,omitempty"`
	// Machine-readable reason code (0 = authorized).
	ReasonCode uint32 `protobuf:"varint,2,opt,name=reason_code,json=reasonCode,proto3" json:"reason_code,omitempty"`
	// Human-readable reason for rejection (empty on success).
	Reason        string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthzRes) Reset() {
	*x = AuthzRes{}
	mi := &file_auth_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthzRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthzRes) ProtoMessage() {}

func (x *AuthzRes) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthzRes.ProtoReflect.Descriptor instead.
func (*AuthzRes) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *AuthzRes) GetAuthorized() bool {
	if x != nil {
		return x.Authorized
	}
	return false
}

func (x *AuthzRes) GetReasonCode() uint32 {
	if x != nil {
		return x.ReasonCode
	}
	return 0
}

func (x *AuthzRes) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_auth_v1_auth_proto protoreflect.FileDescriptor

const file_auth_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x12auth/v1/auth.proto\x12\x0efluxmq.auth.v1\"_\n" +
	"\bAuthnReq\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"y\n" +
	"\bAuthnRes\x12$\n" +
	"\rauthenticated\x18\x01 \x01(\bR\rauthenticated\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x1f\n" +
	"\vreason_code\x18\x03 \x01(\rR\n" +
	"reasonCode\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"q\n" +
	"\bAuthzReq\x12\x1f\n" +
	"\vexternal_id\x18\x01 \x01(\tR\n" +
	"externalId\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12.\n" +
	"\x06action\x18\x03 \x01(\x0e2\x16.fluxmq.auth.v1.ActionR\x06action\"c\n" +
	"\bAuthzRes\x12\x1e\n" +
	"\n" +
	"authorized\x18\x01 \x01(\bR\n" +
	"authorized\x12\x1f\n" +
	"\vreason_code\x18\x02 \x01(\rR\n" +
	"reasonCode\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason*2\n" +
	"\x06Action\x12\x12\n" +
	"\x0eACTION_PUBLISH\x10\x00\x12\x14\n" +
	"\x10ACTION_SUBSCRIBE\x10\x012\x92\x01\n" +
	"\vAuthService\x12B\n" +
	"\fAuthenticate\x12\x18.fluxmq.auth.v1.AuthnReq\x1a\x18.fluxmq.auth.v1.AuthnRes\x12?\n" +
	"\tAuthorize\x12\x18.fluxmq.auth.v1.AuthzReq\x1a\x18.fluxmq.auth.v1.AuthzResB\xad\x01\n" +
	"\x12com.fluxmq.auth.v1B\tAuthProtoP\x01Z2github.com/absmach/fluxmq/pkg/proto/auth/v1;authv1\xa2\x02\x03FAX\xaa\x02\x0eFluxmq.Auth.V1\xca\x02\x0eFluxmq\\Auth\\V1\xe2\x02\x1aFluxmq\\Auth\\V1\\GPBMetadata\xea\x02\x10Fluxmq::Auth::V1b\x06proto3"

var (
	file_auth_v1_auth_proto_rawDescOnce sync.Once
	file_auth_v1_auth_proto_rawDescData []byte
)

func file_auth_v1_auth_proto_rawDescGZIP() []byte {
	file_auth_v1_auth_proto_rawDescOnce.Do(func() {
		file_auth_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_v1_auth_proto_rawDesc), len(file_auth_v1_auth_proto_rawDesc)))
	})
	return file_auth_v1_auth_proto_rawDescData
}

var file_auth_v1_auth_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_auth_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_auth_v1_auth_proto_goTypes = []any{
	(Action)(0),      // 0: fluxmq.auth.v1.Action
	(*AuthnReq)(nil), // 1: fluxmq.auth.v1.AuthnReq
	(*AuthnRes)(nil), // 2: fluxmq.auth.v1.AuthnRes
	(*AuthzReq)(nil), // 3: fluxmq.auth.v1.AuthzReq
	(*AuthzRes)(nil), // 4: fluxmq.auth.v1.AuthzRes
}
var file_auth_v1_auth_proto_depIdxs = []int32{
	0, // 0: fluxmq.auth.v1.AuthzReq.action:type_name -> fluxmq.auth.v1.Action
	1, // 1: fluxmq.auth.v1.AuthService.Authenticate:input_type -> fluxmq.auth.v1.AuthnReq
	3, // 2: fluxmq.auth.v1.AuthService.Authorize:input_type -> fluxmq.auth.v1.AuthzReq
	2, // 3: fluxmq.auth.v1.AuthService.Authenticate:output_type -> fluxmq.auth.v1.AuthnRes
	4, // 4: fluxmq.auth.v1.AuthService.Authorize:output_type -> fluxmq.auth.v1.AuthzRes
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_auth_v1_auth_proto_init() }
func file_auth_v1_auth_proto_init() {
	if File_auth_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_v1_auth_proto_rawDesc), len(file_auth_v1_auth_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_v1_auth_proto_goTypes,
		DependencyIndexes: file_auth_v1_auth_proto_depIdxs,
		EnumInfos:         file_auth_v1_auth_proto_enumTypes,
		MessageInfos:      file_auth_v1_auth_proto_msgTypes,
	}.Build()
	File_auth_v1_auth_proto = out.File
	file_auth_v1_auth_proto_goTypes = nil
	file_auth_v1_auth_proto_depIdxs = nil
}
